"""Editorial bridge: structure, honesty and determinism of generated drafts (no Node needed)."""

from __future__ import annotations

import json
import re
import unicodedata
from itertools import combinations

import pytest

from draft_support import candidate, candidate_dir, clone, load_fixture, retake, temp_repo  # noqa: F401

from roundcraft_miner.draft.case_draft import (
    ORIGIN_LABEL,
    PROPOSED_RUBRIC_NOTE,
    build_case,
    identity_leaks,
    player_facing_text,
)

ID = re.compile(r"^[a-z0-9_]+$")
PID = re.compile(r"\bp\d{2}\b", re.IGNORECASE)
LONG_NUMBER = re.compile(r"\d{17}")


# --- independent re-implementations (do not import the module under test) ---------------------------


def _tokens(text: str) -> list[str]:
    text = unicodedata.normalize("NFKD", text.lower())
    return [t for t in re.split(r"[\W_]+", text) if t]


def _grams(text: str) -> set[str]:
    tokens = _tokens(text)
    return {" ".join(tokens[i : i + 6]) for i in range(len(tokens) - 5)}


NON_PROSE = {"evidenceId", "kind", "timestamp", "caseRevision", "schemaVersion", "editionId", "id"}


def _prose(node):
    if isinstance(node, str):
        yield node
    elif isinstance(node, list):
        for item in node:
            yield from _prose(item)
    elif isinstance(node, dict):
        for key, value in node.items():
            if key not in NON_PROSE:
                yield from _prose(value)


def _brief_text(brief: dict) -> list[str]:
    texts = [brief["title"], brief["focus"]]
    texts += [f["text"] for f in brief["facts"]]
    for key in ("actions", "qualifiers", "evidence", "confidence"):
        texts += [item["label"] for item in brief[key]]
    return texts


def _line_quality(rubric: dict, cell: dict) -> float:
    weights = {d["id"]: d["weight"] for d in rubric["dimensions"]}
    raw = sum(weights[d] * r for d, r in cell["ratings"].items())
    cap = min(cell["caps"]) if cell["caps"] else 100
    return min(raw, cap * 4) / 4


# --- honesty -----------------------------------------------------------------------------------------


def test_draft_status_origin_and_label(candidate):
    case = build_case(candidate)
    assert case["editorial"]["status"] == "draft"
    assert case["origin"] == "synthetic" and case["brief"]["origin"] == "synthetic"
    assert case["edition"]["publicMetadata"]["origin_label"] == "Synthetic scenario — editorial tactical analysis."
    assert ORIGIN_LABEL == "Synthetic scenario — editorial tactical analysis."
    assert "fixture" not in case
    assert case["editorial"]["reviewers"] == []
    edition = case["edition"]
    assert (edition["releaseAt"], edition["officialEndAt"], edition["graceEndAt"]) == (None, None, None)
    assert case["reveal"]["continuation"]["kind"] == "authored"  # a synthetic case may never claim "observed"


def test_editorial_notes_and_issues(candidate):
    case = build_case(candidate)
    editorial = case["editorial"]
    assert editorial["notes"].startswith(PROPOSED_RUBRIC_NOTE)
    assert "PROPOSED RUBRIC — generated by heuristics from category templates; requires human tactical review before technically_validated." in editorial["notes"]
    for note in candidate["reviewNotes"]:
        assert note in editorial["knownIssues"]
    (ref,) = editorial["references"]
    assert ref["kind"] == "source" and "demo_source" in ref["detail"]
    for key in ("sourceId", "candidateId", "map", "round", "decisionTick"):
        assert f"{key}={candidate[key]}" in ref["detail"]
    assert "demoSha256=" in ref["detail"]
    assert "NOT treated as the correct answer" in editorial["notes"]


def test_no_followup_records_known_issue(clone):
    candidate = load_fixture("candidate_ct_hold_nofollowup")
    assert candidate["followUp"] is None
    case = build_case(candidate)
    assert any("Follow-up must be authored: the first change after the decision in the source round was the team's own action." in issue for issue in case["editorial"]["knownIssues"])
    assert case["followup"]["type"] == "new_information"
    assert len(case["followup"]["responses"]) >= 2


def test_no_identities_in_player_facing_text(candidate):
    case = build_case(candidate)
    for text in player_facing_text(case):
        assert not PID.search(text), text
        assert not LONG_NUMBER.search(text), text
    assert identity_leaks(case) == []
    dumped = json.dumps({k: case[k] for k in ("brief", "followup", "reveal", "edition")}, ensure_ascii=False)
    assert not PID.search(dumped) and not LONG_NUMBER.search(dumped)


def test_identities_are_scrubbed_from_candidate_text(retake, clone):
    dirty = clone(retake)
    dirty["playerKnown"]["facts"][0]["text"] += " p07 was on it."
    dirty["playerKnown"]["facts"][1]["basis"] = "STEAM_0:1:12345678 said so"
    dirty["actualLine"] = "HISTORICAL LINE (x). p03 (CT) 76561198000000000 pushed and p04 (T) fell."
    dirty["followUp"]["summary"] = "p09 is spotted in Palace."
    dirty["groundTruth"]["timelineAfter"][1]["description"] = "p02 (CT) killed p06 (T) with awp in Palace 76561198012345678"
    case = build_case(dirty)
    assert identity_leaks(case) == []
    for text in player_facing_text(case):
        assert not PID.search(text) and not LONG_NUMBER.search(text)


def test_brief_never_uses_ground_truth(candidate, clone):
    truth_only = set()
    for enemy in candidate["groundTruth"].get("enemies", []):
        known_places = {e.get("place") for e in candidate["playerKnown"]["enemies"]}
        if enemy["place"] not in known_places:
            truth_only.add(enemy["place"])
            truth_only.add(re.sub(r"(?<=[a-z])(?=[A-Z])", " ", enemy["place"]))
            truth_only.add(str(enemy["x"]))
            truth_only.add(str(enemy["y"]))
    assert truth_only, "fixture must carry an enemy position that only ground truth knows"
    case = build_case(candidate)
    brief_blob = json.dumps(case["brief"], ensure_ascii=False)
    evidence_blob = json.dumps(case["brief"]["evidence"], ensure_ascii=False)
    followup_blob = json.dumps(case["followup"], ensure_ascii=False)
    for value in truth_only:
        assert value not in brief_blob, value
        assert value not in evidence_blob, value
        assert value not in followup_blob, value


def test_brief_followup_rubric_independent_of_ground_truth_and_actual_line(candidate, clone):
    baseline = build_case(candidate)
    altered = clone(candidate)
    altered["groundTruth"] = {"enemies": [{"pid": "p99", "place": "SomewhereElse", "x": 1, "y": 2}], "timelineAfter": [], "outcome": {}}
    altered["actualLine"] = "HISTORICAL LINE (x). Something else entirely happened."
    other = build_case(altered)
    assert other["brief"] == baseline["brief"]
    assert other["followup"] == baseline["followup"]
    assert other["rubric"] == baseline["rubric"]
    assert other["reveal"] != baseline["reveal"]  # the reveal is the only place ground truth may show


def test_followup_uses_only_mined_followup(retake, clone):
    without = clone(retake)
    without["followUp"] = None
    case = build_case(without)
    assert "Palace" not in json.dumps(case["followup"])
    with_follow = build_case(retake)
    assert "Palace" in json.dumps(with_follow["followup"])


# --- structure ---------------------------------------------------------------------------------------


def test_identifiers_and_lengths(candidate):
    case = build_case(candidate)
    brief, followup, reveal = case["brief"], case["followup"], case["reveal"]
    for value in (case["caseId"], case["editorial"]["revision"], case["editorial"]["rubricRevision"], case["edition"]["editionId"]):
        assert ID.match(value) and len(value) <= 80
    assert case["caseId"].startswith("case_") and case["caseId"] == case["caseId"].lower()
    assert brief["caseRevision"] == followup["caseRevision"] == reveal["caseRevision"] == case["rubric"]["caseRevision"] == case["editorial"]["revision"]
    assert brief["editionId"] == case["edition"]["editionId"]
    assert case["rubric"]["rubricRevision"] == case["editorial"]["rubricRevision"]
    meta = case["edition"]["publicMetadata"]
    assert 5 <= meta["estimated_minutes"] <= 8 and 1 <= len(meta["focus"]) <= 80 and meta["case_number"] >= 1
    assert re.match(r"^\d{4}-\d{2}-\d{2}$", meta["edition_date_utc"])
    assert 1 <= len(brief["title"]) <= 160 and 1 <= len(brief["focus"]) <= 240
    assert 1 <= len(brief["facts"]) <= 30 and all(1 <= len(f["text"]) <= 500 for f in brief["facts"])
    assert len(brief["evidence"]) == 5 and len(brief["confidence"]) == 4
    assert [c["id"] for c in brief["confidence"]] == ["guessing", "leaning", "fairly_sure", "strong_read"]
    assert 3 <= len(brief["actions"]) <= 5 and 2 <= len(brief["qualifiers"]) <= 20
    for action in brief["actions"]:
        assert 2 <= len(action["qualifierIds"]) <= 4 and len(action["label"]) <= 120
    for group in ("facts", "actions", "qualifiers", "evidence"):
        ids = [item["id"] for item in brief[group]]
        assert len(ids) == len(set(ids)) and all(ID.match(i) for i in ids)
    assert {f["status"] for f in brief["facts"]} <= {"confirmed", "last_seen", "inferred", "unknown"}
    assert 2 <= len(followup["responses"]) <= 4 and 1 <= len(followup["updates"]) <= 20
    assert {u["status"] for u in followup["updates"]} <= {"new", "changed", "expired", "unchanged"}
    assert 1 <= len(reveal["continuation"]["events"]) <= 12
    assert 18 <= len(reveal["principle"]) <= 320
    debrief = reveal["debrief"]
    assert 1 <= len(debrief["evidenceReview"]) <= 5
    evidence_ids = {e["id"] for e in brief["evidence"]}
    assert all(r["evidenceId"] in evidence_ids for r in debrief["evidenceReview"])
    for text in _prose(reveal):
        assert 1 <= len(text) <= 1200 or text == reveal["principle"]


def test_facts_map_player_known_statuses(retake):
    case = build_case(retake)
    by_text = {f["text"]: f["status"] for f in case["brief"]["facts"]}
    mined = {f["text"]: f["status"] for f in retake["playerKnown"]["facts"]}
    for text, status in mined.items():
        match = [s for t, s in by_text.items() if t.startswith(text.rstrip("."))]
        assert match == [status], (text, status, match)
    assert any(f["status"] == "last_seen" for f in case["brief"]["facts"])
    for fact in case["brief"]["facts"]:
        if fact["status"] == "last_seen":
            assert re.search(r"\bago\b|\d+\s?s\b|second", fact["text"])


def test_evidence_options_come_from_player_known_signals(retake):
    case = build_case(retake)
    labels = {e["label"] for e in case["brief"]["evidence"]}
    assert "Bomb timer" in labels and "Alive count" in labels
    assert "Attacker last seen in Connector" in labels


# --- rubric ------------------------------------------------------------------------------------------


def test_rubric_matrix_is_complete(candidate):
    case = build_case(candidate)
    brief, rubric, followup = case["brief"], case["rubric"], case["followup"]
    dims = {d["id"] for d in rubric["dimensions"]}
    assert sum(d["weight"] for d in rubric["dimensions"]) == 100
    cells = {(c["actionId"], c["qualifierId"]) for c in rubric["main"]}
    expected = {(a["id"], q) for a in brief["actions"] for q in a["qualifierIds"]}
    assert cells == expected and len(rubric["main"]) == len(expected)
    for cell in rubric["main"]:
        assert set(cell["ratings"]) == dims and all(isinstance(v, int) and 0 <= v <= 4 for v in cell["ratings"].values())
        assert len(cell["caps"]) <= 8 and all(0 <= c <= 100 for c in cell["caps"])
    evidence_ids = sorted(e["id"] for e in brief["evidence"])
    pairs = {tuple(p) for p in combinations(evidence_ids, 2)}
    assert len(pairs) == 10
    for action in brief["actions"]:
        rows = [tuple(sorted(c["evidenceIds"])) for c in rubric["evidence"] if c["actionId"] == action["id"]]
        assert len(rows) == 10 and set(rows) == pairs
    assert all(isinstance(c["points"], int) and 0 <= c["points"] <= 20 for c in rubric["evidence"])
    published = {r["id"] for r in followup["responses"]}
    assert rubric["followup"]["type"] == followup["type"] == "new_information"
    assert {r["responseId"] for r in rubric["followup"]["responses"]} == published
    qualities = [r["quality"] for r in rubric["followup"]["responses"]]
    assert all(isinstance(q, int) and 0 <= q <= 100 for q in qualities) and max(qualities) - min(qualities) >= 20


def test_rubric_reaches_best_supported_and_offers_alternatives(candidate):
    case = build_case(candidate)
    rubric = case["rubric"]
    by_action: dict[str, float] = {}
    for cell in rubric["main"]:
        by_action[cell["actionId"]] = max(by_action.get(cell["actionId"], 0), _line_quality(rubric, cell))
    assert max(by_action.values()) >= 90
    assert sum(1 for q in by_action.values() if q >= 70) >= 2


def test_best_action_is_not_always_first(retake, clone):
    positions = set()
    for index in range(60):
        variant = clone(retake)
        variant["candidateId"] = f"cand_{index:012x}"
        case = build_case(variant)
        rubric = case["rubric"]
        best: dict[str, float] = {}
        for cell in rubric["main"]:
            best[cell["actionId"]] = max(best.get(cell["actionId"], 0), _line_quality(rubric, cell))
        top = max(best.values())
        order = [a["id"] for a in case["brief"]["actions"]]
        leaders = [i for i, a in enumerate(order) if best[a] == top]
        assert leaders and 0 not in leaders  # the best-supported action is never listed first
        positions.add(leaders[0])
    assert len(positions) >= 2, "the best action should move around between candidates"


def test_best_followup_response_is_not_always_first(retake, clone):
    firsts = set()
    for index in range(40):
        variant = clone(retake)
        variant["candidateId"] = f"cand_{index:012x}"
        case = build_case(variant)
        # The strongest line after the update is the one whose "stay with it" cell scores highest.
        staying = {r["responseId"]: r["quality"] for r in case["rubric"]["followup"]["responses"]
                   if r["responseId"] == f"now_{r['actionId']}"}
        best = max(staying, key=staying.get)
        assert case["followup"]["responses"][0]["id"] != best
        firsts.add(case["followup"]["responses"][0]["id"])
    assert len(firsts) >= 2


def test_priors_follow_the_state(retake, clone):
    """A short clock makes saving the leading line; a comfortable clock with even numbers makes a group retake lead."""
    short = clone(retake)
    short["playerKnown"]["clock"]["bombSecondsLeft"] = 6.0
    long_ = build_case(retake)
    late = build_case(short)

    def leader(case):
        rubric, best = case["rubric"], {}
        for cell in rubric["main"]:
            best[cell["actionId"]] = max(best.get(cell["actionId"], 0), _line_quality(rubric, cell))
        return max(best, key=best.get)

    assert leader(long_) == "group_retake"
    assert leader(late) == "save_weapons"


def _followup_cells(case):
    return {(c["actionId"], c["responseId"].removeprefix("now_")): c["quality"] for c in case["rubric"]["followup"]["responses"]}


def test_followup_scores_follow_the_locked_line(retake, clone):
    cells = _followup_cells(build_case(retake))
    # The update leaves the grouped retake strongest: staying with it beats every reversal.
    assert cells[("group_retake", "group_retake")] == max(cells[("group_retake", now)] for now in
                                                          ("take_information", "split_retake", "save_weapons", "group_retake"))
    # The same answer scores differently after different locked lines.
    assert cells[("group_retake", "group_retake")] > cells[("save_weapons", "group_retake")] > cells[("save_weapons", "split_retake")]
    # A weaker call corrected towards the strongest line beats holding on to it.
    assert cells[("take_information", "group_retake")] > cells[("take_information", "take_information")]

    urgent = clone(retake)
    urgent["followUp"]["knowledgeAfter"]["clock"]["bombSecondsLeft"] = 4.0
    cells = _followup_cells(build_case(urgent))
    # With 4 s left no retake can finish: a retaker does best to save, and a saver to stay saved.
    assert max(cells[("group_retake", now)] for now in ("group_retake", "save_weapons")) == cells[("group_retake", "save_weapons")]
    assert cells[("save_weapons", "save_weapons")] == max(cells.values())


# --- determinism and disclosure ----------------------------------------------------------------------


def test_deterministic(candidate):
    first = json.dumps(build_case(candidate), ensure_ascii=False)
    second = json.dumps(build_case(json.loads(json.dumps(candidate))), ensure_ascii=False)
    reordered = json.loads(json.dumps(candidate, sort_keys=True))
    third = json.dumps(build_case(reordered), ensure_ascii=False)
    assert first == second == third


def test_case_id_override_and_derivation(retake):
    case = build_case(retake, case_id="case_custom_retake_001")
    assert case["caseId"] == "case_custom_retake_001"
    assert case["editorial"]["revision"] == "cr_custom_retake_001"
    assert case["edition"]["editionId"] == "ed_custom_retake_001"
    with pytest.raises(ValueError):
        build_case(retake, case_id="Not Valid")


def test_no_six_word_overlap_between_brief_and_later_phases(candidate):
    case = build_case(candidate)
    banned = set().union(*(_grams(t) for t in _brief_text(case["brief"])))
    for section in ("followup", "reveal"):
        for text in _prose(case[section]):
            shared = _grams(text) & banned
            assert not shared, f"{section}: {text!r} shares {sorted(shared)[:2]}"


def test_overlapping_candidate_wording_is_repaired(retake, clone):
    """Follow-up text copied from a brief fact must not survive verbatim."""
    dirty = clone(retake)
    dirty["followUp"]["newFacts"][0]["text"] = "The bomb is planted at A; 31 s remain on the bomb timer."
    dirty["followUp"]["summary"] = "Your team is positioned: 2 in Ramp, 1 in Stairs."
    case = build_case(dirty)
    banned = set().union(*(_grams(t) for t in _brief_text(case["brief"])))
    for text in _prose(case["followup"]):
        assert not (_grams(text) & banned)
    assert any("auto-adjusted" in issue for issue in case["editorial"]["knownIssues"])


# --- template families ---------------------------------------------------------------------------------


def _as_t_precommit(candidate: dict, clone) -> dict:
    variant = clone(candidate)
    variant["perspective"] = "T"
    variant["playerKnown"]["perspective"] = "T"
    variant["playerKnown"]["bomb"] = {"status": "carried", "knowledge": "confirmed", "place": "Ramp"}
    variant["playerKnown"]["clock"] = {"roundSecondsLeft": 50.0, "bombSecondsLeft": None}
    variant["category"] = "late_round_no_plant"
    variant["candidateId"] = "cand_0123456789ab"
    variant["followUp"] = None
    return variant


def test_execute_family_and_economy_save_option(retake, clone):
    t_case = build_case(_as_t_precommit(retake, clone))
    ids = {a["id"] for a in t_case["brief"]["actions"]}
    assert {"commit_execute", "default_take_info"} <= ids and "save_weapons_t" not in ids
    save = _as_t_precommit(retake, clone)
    save["category"] = "economy_save"
    save["playerKnown"]["alive"] = {"own": 2, "enemy": 4}
    save["playerKnown"]["own"] = save["playerKnown"]["own"][:2]
    save["playerKnown"]["clock"]["roundSecondsLeft"] = 20.0
    ids = {a["id"] for a in build_case(save)["brief"]["actions"]}
    assert "save_weapons_t" in ids
    assert 3 <= len(ids) <= 5


def test_situation_family_from_category_and_bomb_state(retake, clone):
    from roundcraft_miner.draft.features import extract_features

    assert extract_features(retake).situation == "retake"
    as_t = clone(retake)
    as_t["perspective"] = "T"
    assert extract_features(as_t).situation == "post_plant_hold"
    pre = _as_t_precommit(retake, clone)
    assert extract_features(pre).situation == "execute_or_default"
    pre["perspective"] = "CT"
    assert extract_features(pre).situation == "hold_or_rotate"


def test_template_prose_never_copies_option_labels():
    """Debrief/principle/response templates must not share 6-word runs with the brief labels they refer to."""
    from roundcraft_miner.draft.templates import SITUATIONS, now_label

    for sit in SITUATIONS.values():
        banned = _grams(sit.title.format(map="Mirage")) | _grams(sit.focus)
        for action in sit.actions:
            for label in (action.label.format(place="Connector"), action.label_no_place, *(q.label for q in action.qualifiers)):
                banned |= _grams(label)
        prose = [sit.principle, *sit.evidence_notes.values(), *(now_label(action.id, "Connector") for action in sit.actions),
                  *(now_label(action.id, None) for action in sit.actions)]
        for action in sit.actions:
            prose += [action.why, action.cost, action.assumption, action.breaks, f"The closest alternative was {action.alt}.",
                      action.cf_fact, action.cf_effect]
        for text in prose:
            assert not (_grams(text) & banned), (sit.id, text)


def test_stale_sightings_are_not_named_as_targets(retake, clone):
    stale = clone(retake)
    stale["playerKnown"]["enemies"][0]["ageSeconds"] = 40.0
    labels = " ".join(a["label"] for a in build_case(stale)["brief"]["actions"])
    assert "Connector" not in labels and "nearest entrance" in labels
    fresh = build_case(retake)
    assert "Connector" in " ".join(a["label"] for a in fresh["brief"]["actions"])


def test_public_reveal_has_no_internal_jargon(candidate):
    case = build_case(candidate)
    text = " ".join(_prose(case["reveal"]) ) + " " + " ".join(_prose(case["followup"]))
    for jargon in ("follow-up kind", "enemy_spotted", "tier", "NORMALISED", "candidate", "groundTruth", "playerKnown"):
        assert jargon not in text, jargon


def test_break_overlap_prefers_meaning_preserving_rewrites():
    from roundcraft_miner.draft.text import break_overlap, shingles

    banned = set(shingles("One attacker was last seen in Top of Mid 23 s ago."))
    text, changed = break_overlap("One attacker was last seen in Top of Mid 30 s ago.", banned)
    assert changed and "last spotted in" in text and not (set(shingles(text)) & banned)
    # no rewrite available: falls back to a bridge word, still overlap free
    banned = set(shingles("alpha bravo charlie delta echo foxtrot golf"))
    text, changed = break_overlap("alpha bravo charlie delta echo foxtrot golf", banned)
    assert changed and not (set(shingles(text)) & banned)


# --- real mined candidates (skipped when data-local has none) ------------------------------------------


def _real_candidates():
    from roundcraft_miner import paths

    root = paths.data_root() / "candidates"
    return sorted(root.glob("*/cand_*/candidate.json")) if root.exists() else []


@pytest.mark.skipif(not _real_candidates(), reason="no mined candidates under data-local/candidates")
def test_every_real_candidate_builds_a_clean_draft():
    banned_pid = PID
    seen_families = set()
    for path in _real_candidates():
        candidate = json.loads(path.read_text(encoding="utf-8"))
        case = build_case(candidate)
        banned = set().union(*(_grams(t) for t in _brief_text(case["brief"])))
        for section in ("followup", "reveal"):
            for text in _prose(case[section]):
                assert not (_grams(text) & banned), (path.parent.name, section, text)
        assert identity_leaks(case) == [], path.parent.name
        assert not banned_pid.search(json.dumps(case["brief"]) + json.dumps(case["followup"]) + json.dumps(case["reveal"]))
        assert len(case["brief"]["evidence"]) == 5 and 3 <= len(case["brief"]["actions"]) <= 5
        assert case["editorial"]["status"] == "draft"
        rubric = case["rubric"]
        best = max(_line_quality(rubric, c) for c in rubric["main"])
        assert best >= 90, (path.parent.name, best)
        seen_families.add((candidate["category"], candidate["perspective"]))
    assert seen_families
