"""Editorial bridge: mined Candidate -> Roundcraft case DRAFT JSON (content/cases/<caseId>.json).

Hard rules (see tools/case-miner README and AGENTS.md):
  * the output is always status "draft", origin "synthetic", with the exact synthetic origin label;
  * the BRIEF and its evidence/actions use only candidate.playerKnown (+ map/perspective/category);
  * the FOLLOW-UP uses only candidate.followUp; the REVEAL may use groundTruth and actualLine;
  * the rubric is a PROPOSAL from documented heuristics (templates.py / priors.py), never tactical truth;
  * no player names, Steam IDs, team names or pids in any player-facing text.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .. import paths
from ..model import read_json
from .features import Features, extract_features
from .priors import (
    ActionPrior,
    MainPrior,
    Signal,
    choose_evidence,
    compute_main_prior,
    evidence_points,
    followup_class,
    followup_qualities,
    order_actions,
    order_qualifiers,
    order_responses,
    stable_hash,
)
from .templates import SITUATIONS, Situation
from .text import (
    break_overlap,
    clock_label,
    has_identity,
    map_display,
    map_slug,
    pretty_place,
    scrub,
    seconds_phrase,
    shingles,
    slug,
    truncate,
)
from .timeline import render_outcome, render_timeline

ORIGIN_LABEL = "Synthetic scenario — editorial tactical analysis."
PROPOSED_RUBRIC_NOTE = (
    "PROPOSED RUBRIC — generated by heuristics from category templates; "
    "requires human tactical review before technically_validated."
)
AUTHOR = "roundcraft-miner (generated draft)"
CONFIDENCE = [
    {"id": "guessing", "label": "Guessing"},
    {"id": "leaning", "label": "Leaning"},
    {"id": "fairly_sure", "label": "Fairly sure"},
    {"id": "strong_read", "label": "Strong read"},
]
FACT_STATUSES = ("confirmed", "last_seen", "inferred", "unknown")
MAX_FACTS = 14
PLACEHOLDER_CASE_NUMBER = 900
PLACEHOLDER_EDITION_DATE = "2099-01-01"
CASE_ID_MAX = 75  # leaves room for the cr_/rr_/ed_ prefixes inside the 80-char identifier limit


class DraftRefused(RuntimeError):
    """Raised when writing a draft would overwrite something it must not."""


# ---------------------------------------------------------------------------
# Identifiers
# ---------------------------------------------------------------------------


def make_case_id(candidate: dict[str, Any], case_id: str | None = None) -> str:
    if case_id:
        cid = slug(case_id, max_len=CASE_ID_MAX)
        if cid != case_id:
            raise ValueError(f"case id {case_id!r} must match ^[a-z0-9_]+$ (max {CASE_ID_MAX} chars)")
        return cid
    short = slug(str(candidate["candidateId"]).removeprefix("cand_"), max_len=8)[:6]
    category = slug(candidate.get("category", "case"), max_len=28)
    return f"case_{map_slug(candidate.get('map', 'map'))}_{category}_{short}"[:CASE_ID_MAX].rstrip("_")


def derived_ids(case_id: str) -> dict[str, str]:
    stem = case_id.removeprefix("case_")
    return {"revision": f"cr_{stem}", "rubricRevision": f"rr_{stem}", "editionId": f"ed_{stem}"}


def _ident(text: str, taken: set[str], fallback: str) -> str:
    base = slug(text, max_len=60) if text else fallback
    candidate, n = base, 2
    while candidate in taken:
        candidate = f"{base}_{n}"
        n += 1
    taken.add(candidate)
    return candidate


# ---------------------------------------------------------------------------
# Brief (player-known only)
# ---------------------------------------------------------------------------

_FACT_CLASS_KEYWORDS: tuple[tuple[int, tuple[str, ...]], ...] = (
    (0, ("clock", "timer", "bomb", "time")),
    (1, ("alive", "players", "head")),
    (2, ("utility", "smoke", "flash", "grenade", "molotov", "he_")),
    (3, ("seen", "spotted", "sight", "heard")),
    (4, ("unknown", "unaccounted", "hidden")),
)


def _fact_class(fact: dict[str, Any]) -> int:
    hay = f"{fact.get('id', '')} {fact.get('text', '')}".lower()
    for cls, words in _FACT_CLASS_KEYWORDS:
        if any(word in hay for word in words):
            return cls
    if fact.get("status") in ("last_seen", "confirmed"):
        return 3
    return 5


def _plural(n: int, word: str, plural: str | None = None) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {plural or word + 's'}"


def _utility_sentence(f: Features) -> str | None:
    parts = []
    for kind, one, many in (("smoke", "smoke", "smokes"), ("flash", "flash", "flashes"),
                            ("he", "HE grenade", "HE grenades"), ("molotov", "molotov", "molotovs"),
                            ("decoy", "decoy", "decoys")):
        count = f.util.get(kind, 0)
        if count:
            parts.append(_plural(count, one, many))
    if not parts:
        return None
    joined = parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]
    return f"Your team still holds {joined}."


def build_facts(candidate: dict[str, Any], f: Features) -> tuple[list[dict[str, str]], list[str]]:
    issues: list[str] = []
    view = candidate["playerKnown"]
    taken: set[str] = set()
    mined: list[tuple[int, int, dict[str, str]]] = []
    for index, raw in enumerate(view.get("facts") or []):
        status = raw.get("status")
        if status not in FACT_STATUSES:
            issues.append(f"Mined fact {raw.get('id')!r} had an unrecognised status {status!r}; treated as 'unknown'.")
            status = "unknown"
        text = scrub(str(raw.get("text", "")).strip())
        basis = re.sub(r"\brounds? \d+(?:, \d+)*", "recent rounds", scrub(str(raw.get("basis", "")).strip()))
        if status == "inferred" and basis and "basis" not in text.lower() and len(text) + len(basis) < 470:
            text = f"{text.rstrip('.')}. Basis: {basis.rstrip('.')}."
        if not text:
            continue
        mined.append((_fact_class(raw), index, {"id": _ident(str(raw.get("id", "")), taken, f"fact_{index + 1}"),
                                                "status": status, "text": truncate(text, 500)}))
        if status == "last_seen" and not any(ch.isdigit() for ch in text) and "ago" not in text.lower():
            issues.append(f"Fact {mined[-1][2]['id']!r} is last_seen but its text states no age.")

    derived: list[tuple[int, dict[str, str]]] = []
    classes = {cls for cls, _, _ in mined}
    perspective_fact = {"id": _ident("perspective", taken, "perspective"), "status": "confirmed",
                        "text": f"You play the {f.perspective} side on {map_display(f.map_name)}."}
    if 0 not in classes and f.time_left is not None:
        if f.time_kind == "bomb":
            site = f" on site {f.bomb_site}" if f.bomb_site else ""
            text = f"The bomb is planted{site}. About {seconds_phrase(f.time_left)} are left before it explodes."
            fid = "bomb_timer"
        else:
            text = f"About {seconds_phrase(f.time_left)} are left on the round clock."
            fid = "round_clock"
        derived.append((0, {"id": _ident(fid, taken, fid), "status": "confirmed", "text": text}))
    if 1 not in classes:
        derived.append((1, {"id": _ident("alive_count", taken, "alive_count"), "status": "confirmed",
                            "text": f"Your team has {f.own_alive} players alive and the opposing team has {f.enemy_alive}."}))
    if 2 not in classes:
        sentence = _utility_sentence(f)
        if sentence:
            derived.append((2, {"id": _ident("own_utility", taken, "own_utility"), "status": "confirmed", "text": sentence}))
    if f.perspective == "CT" and f.own_alive > 0:
        # Kits are visible on the scoreboard to teammates, so this is known to the deciding team.
        kit_text = ("No one on your team carries a defuse kit." if f.own_kit == 0 else
                    f"{f.own_kit} of your {f.own_alive} alive players carry a defuse kit.")
        derived.append((2, {"id": _ident("defuse_kits", taken, "defuse_kits"), "status": "confirmed", "text": kit_text}))
    if 4 not in classes and f.unknown_enemies > 0 and not any(m[2]["status"] == "unknown" for m in mined):
        derived.append((4, {"id": _ident("unknown_positions", taken, "unknown_positions"), "status": "unknown",
                            "text": f"{_plural(f.unknown_enemies, f.enemy_noun)} cannot currently be placed."}))

    # mined facts keep their source order inside a class; derived facts sort ahead of mined ones of the same class
    keyed = [(cls, 0, i, fact) for i, (cls, fact) in enumerate(derived)] + [(cls, 1, idx, fact) for cls, idx, fact in mined]
    facts = [perspective_fact] + [item[3] for item in sorted(keyed, key=lambda item: item[:3])]
    if len(facts) > MAX_FACTS:
        issues.append(f"Brief facts were capped at {MAX_FACTS} by priority (clock/bomb, alive counts, utility, sightings, unknowns); "
                      f"{len(facts) - MAX_FACTS} lower-priority fact(s) were dropped.")
        facts = facts[:MAX_FACTS]
    if not any(fact["status"] in ("inferred", "unknown") for fact in facts):
        issues.append("No fact is marked inferred or unknown; the brief presents nothing as uncertain.")
    return facts, issues


def build_brief(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str],
                main: MainPrior, evidence: list[Signal], actions_ordered: list[ActionPrior]) -> tuple[dict[str, Any], list[str]]:
    facts, issues = build_facts(candidate, f)
    qualifiers: list[dict[str, str]] = []
    actions: list[dict[str, Any]] = []
    for action in actions_ordered:
        quals = order_qualifiers(action.qualifiers, candidate["candidateId"], action.template.id)
        for q in quals:
            qualifiers.append({"id": q.id, "label": q.label})
        actions.append({"id": action.template.id, "label": truncate(scrub(action.label), 120),
                        "qualifierIds": [q.id for q in quals]})
    brief = {
        "schemaVersion": 1,
        "editionId": ids["editionId"],
        "caseRevision": ids["revision"],
        "title": sit.title.format(map=map_display(f.map_name)),
        "focus": sit.focus,
        "origin": "synthetic",
        "facts": facts,
        "actions": actions,
        "qualifiers": qualifiers,
        "evidence": [{"id": s.id, "label": scrub(s.label)} for s in evidence],
        "confidence": [dict(c) for c in CONFIDENCE],
    }
    return brief, issues


# ---------------------------------------------------------------------------
# Follow-up (candidate.followUp only)
# ---------------------------------------------------------------------------

_HEADINGS = (
    ("plant", "The bomb is planted"),
    ("defus", "A defuse begins"),
    ("kill", "A player is eliminated"),
    ("elimin", "A player is eliminated"),
    ("spot", "A new sighting"),
    ("seen", "A new sighting"),
    ("heard", "A new sound"),
    ("sound", "A new sound"),
    ("utility", "Utility is seen"),
)


def _heading(kind: str) -> str:
    kind = (kind or "").lower()
    for key, heading in _HEADINGS:
        if key in kind:
            return heading
    return "The round moves on"


def build_followup(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str],
                   brief_fact_ids: set[str]) -> tuple[dict[str, Any], dict[str, int], str, str, list[str]]:
    issues: list[str] = []
    follow = candidate.get("followUp")
    cls, cls_text, after = followup_class(sit, f, follow, candidate)
    qualities = followup_qualities(sit, cls)
    responses = order_responses(list(sit.responses), qualities, candidate["candidateId"])
    updates: list[dict[str, str]] = []
    taken: set[str] = set()
    if follow is None:
        issues.append("No mined follow-up; follow-up needs authoring (a generic, conservative follow-up was generated).")
        heading = "Time passes"
        stimulus = sit.generic_followup_stimulus
        updates.append({"id": "no_new_contact", "status": "unchanged", "text": "No new position has been confirmed."})
        taken.add("no_new_contact")
    else:
        heading = _heading(follow.get("kind", ""))
        delta = follow.get("t", 0) - candidate.get("decisionT", 0)
        summary = scrub(str(follow.get("summary", "")).strip())
        stimulus = f"After about {seconds_phrase(delta)}: {summary}" if delta >= 1 and summary else summary
        for index, fact in enumerate(follow.get("newFacts") or []):
            status = fact.get("status")
            text = scrub(str(fact.get("text", "")).strip())
            if not text:
                continue
            label = {"last_seen": "last seen", "inferred": "inferred", "unknown": "unknown"}.get(status or "")
            if label and label not in text.lower():
                text = f"{label.capitalize()}: {text}"
            uid = _ident(str(fact.get("id", "")), taken, f"update_{index + 1}")
            updates.append({"id": uid, "status": "changed" if fact.get("id") in brief_fact_ids else "new",
                            "text": truncate(text, 500)})
        mined_ids = " ".join(str(fact.get("id", "")) for fact in follow.get("newFacts") or [])
        mined_text = " ".join(update["text"].lower() for update in updates)
        if after is not None:
            if after.time_left is not None and not re.search(r"\b(bomb_planted|clock)", mined_ids) and "remain on the" not in mined_text:
                noun = "bomb timer" if after.time_kind == "bomb" else "round clock"
                updates.append({"id": _ident("clock_now", taken, "clock_now"), "status": "changed",
                                "text": f"About {seconds_phrase(after.time_left)} now remain on the {noun}."})
            if (after.own_alive, after.enemy_alive) != (f.own_alive, f.enemy_alive) and "alive_" not in mined_ids:
                updates.append({"id": _ident("alive_now", taken, "alive_now"), "status": "changed",
                                "text": f"Your team now has {after.own_alive} players alive and the opposing team has {after.enemy_alive}."})
        if not updates:
            updates.append({"id": "change", "status": "new", "text": stimulus or "The situation has changed."})
        if not stimulus:
            stimulus = "The situation has changed."
    followup = {
        "schemaVersion": 1,
        "caseRevision": ids["revision"],
        "type": "new_information",
        "heading": heading,
        "stimulus": truncate(stimulus, 800),
        "updates": updates[:20],
        "responses": [{"id": r.id, "label": r.label} for r in responses],
    }
    return followup, qualities, cls, cls_text, issues


# ---------------------------------------------------------------------------
# Reveal (groundTruth / actualLine allowed)
# ---------------------------------------------------------------------------


_HISTORICAL_PREFIX = re.compile(r"^HISTORICAL LINE \([^)]*\)\.?\s*")


def _lower_first(text: str) -> str:
    """Lower-case the first word of a sentence unless it is an acronym or a side name (CT, T)."""
    first = text.split(" ", 1)[0].strip(",.:;")
    if not text or first in ("T", "CT") or (len(first) > 1 and first.isupper()):
        return text
    return text[0].lower() + text[1:]


_FOLLOWUP_REASONING = {
    "position_info": "the new information shows where an opponent is or what utility they have used, so adapting the plan is worth more than repeating it",
    "enemy_loss": "an opponent has been eliminated, which favours pressing the advantage instead of changing course",
    "own_loss": "a teammate has been eliminated, which changes the numbers and calls for an adjusted plan",
    "bomb_event": "the state of the bomb has changed, which changes what the plan is for",
    "default": "the change is modest, so adjusting to it is slightly better than repeating the plan unchanged",
    "no_followup": "no new information was mined, so the proposed answers are close together and only weakly ranked",
}


def _followup_reasoning(cls_key: str, sit: Situation) -> str:
    if cls_key == "urgent":
        return f"the state is urgent: {sit.urgent_text}"
    return _FOLLOWUP_REASONING.get(cls_key, _FOLLOWUP_REASONING["default"])


def build_reveal(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str], main: MainPrior,
                 evidence: list[Signal], qualities: dict[str, int], cls_key: str) -> tuple[dict[str, Any], list[str]]:
    issues: list[str] = []
    events, timeline_issues, raw_actions = render_timeline(candidate, f)
    issues.extend(timeline_issues)
    lead, second = main.actions[0], main.actions[1]
    follow = candidate.get("followUp")
    actual = _HISTORICAL_PREFIX.sub("", scrub(str(candidate.get("actualLine", "")).strip()))
    if actual:
        round_action = f"In the source round, {_lower_first(actual)}"
    else:
        round_action = "The source round's line was not recorded for this decision point."
        issues.append("candidate.actualLine is empty; the comparison has no historical line.")
    if follow:
        material = f"The information that arrived after the decision: {scrub(str(follow.get('summary', '')).strip())}"
    else:
        material = "No decisive new information was mined between the decision point and the outcome."
    outcome = render_outcome(candidate, f, winner_only=bool(events and raw_actions))
    round_followup = (
        "After the decision the source round continued: " + " ".join(raw_actions[:3])
        if raw_actions else "The mined data records no further events after the decision point."
    )
    if outcome:
        round_followup = f"{round_followup} {outcome}"

    best_response = max(sit.responses, key=lambda r: qualities[r.id])
    why = lead.template.why
    if f.time_left is not None:
        why += (f" Here, {f.own_alive} players faced {f.enemy_alive} with about {seconds_phrase(f.time_left)} left.")
    else:
        why += f" Here, {f.own_alive} players faced {f.enemy_alive}."
    alt_text = f"The closest alternative was {second.template.alt}."

    weights = {s.id: lead.template.evidence_weights.get(s.cls, sit.evidence_weights.get(s.cls, 1)) for s in evidence}
    reviewed = sorted(evidence, key=lambda s: (-weights[s.id], s.id))[:3]
    review_entries = []
    for s in reviewed:
        explanation = sit.evidence_notes.get(s.cls, "This signal bears on the decision.")
        extra = _evidence_specific(s, f)
        review_entries.append({"evidenceId": s.id, "explanation": f"{explanation} {extra}".strip()})

    reveal = {
        "schemaVersion": 1,
        "caseRevision": ids["revision"],
        "continuation": {"kind": "authored", "events": events},
        "comparison": {"roundAction": truncate(round_action, 1200), "materialInformation": truncate(material, 1200),
                       "roundFollowup": truncate(round_followup, 1200)},
        "debrief": {
            "whyItWorks": truncate(why, 1200),
            "cost": lead.template.cost,
            "assumption": lead.template.assumption,
            "breaksWhen": lead.template.breaks,
            "evidenceReview": review_entries,
            "followupReview": truncate(
                f"The proposed best answer to the new information was: {best_response.label}. "
                f"Reasoning: {_followup_reasoning(cls_key, sit)}.", 1200),
            "strongestAlternative": truncate(alt_text, 1200),
            "counterfactual": {"changedFact": lead.template.cf_fact, "effect": lead.template.cf_effect},
            "method": (
                "Synthetic scenario inspired by a decision point in a recorded demo. The situation was rebuilt from anonymised "
                "game data, the options and reasoning are editorial templates, and the source round's line is shown for comparison "
                "only: it is not treated as the correct answer, and this is not a reconstruction of the match."
            ),
            "sources": [{
                "label": "Roundcraft editorial analysis",
                "detail": "Demo-grounded synthetic scenario. No match, team or player is identified.",
            }],
        },
        "principle": sit.principle,
    }
    return reveal, issues


def _evidence_specific(s: Signal, f: Features) -> str:
    if s.cls == "bomb_timer" and f.time_left is not None:
        return f"Here the timer stood near {seconds_phrase(f.time_left)}."
    if s.cls == "clock" and f.time_left is not None:
        return f"Here the round clock stood near {seconds_phrase(f.time_left)}."
    if s.cls == "alive_count":
        return f"Here it was {f.own_alive} against {f.enemy_alive}."
    if s.cls == "own_utility":
        n = f.util_total
        return f"Here the team held {_plural(n, 'utility item')}."
    if s.cls == "enemy_seen":
        index = int(s.id.rsplit("_", 1)[-1]) - 1
        places = [e for e in sorted(f.known_enemies, key=lambda e: (e.age if e.age is not None else 0.0, e.place or "")) if e.place]
        uniq: list[Any] = []
        for e in places:
            if all(e.place != o.place for o in uniq):
                uniq.append(e)
        if 0 <= index < len(uniq) and uniq[index].age is not None:
            if uniq[index].age < 1.5:
                return "That sighting was current."
            return f"That sighting was about {seconds_phrase(uniq[index].age)} old."
    if s.cls == "enemy_unknown":
        return f"Here {_plural(f.unknown_enemies, f.enemy_noun)} could not be placed."
    return ""


# ---------------------------------------------------------------------------
# Rubric (heuristic proposal)
# ---------------------------------------------------------------------------


def build_rubric(sit: Situation, ids: dict[str, str], main: MainPrior, brief: dict[str, Any],
                 evidence: list[Signal], qualities: dict[str, int], followup: dict[str, Any]) -> dict[str, Any]:
    by_id = {a.template.id: a for a in main.actions}
    dim_ids = [d for d, _ in sit.dims]
    main_cells: list[dict[str, Any]] = []
    evidence_cells: list[dict[str, Any]] = []
    for action in brief["actions"]:
        prior = by_id[action["id"]]
        quals = {q.id: q for q in prior.qualifiers}
        for qid in action["qualifierIds"]:
            q = quals[qid]
            main_cells.append({"actionId": action["id"], "qualifierId": qid,
                               "ratings": {dim_ids[0]: q.ratings[0], dim_ids[1]: q.ratings[1]},
                               "caps": sorted(prior.caps)[:1] if prior.caps else []})
        points = evidence_points(sit, prior.template, evidence)
        for (a, b), pts in sorted(points.items()):
            evidence_cells.append({"actionId": action["id"], "evidenceIds": [a, b], "points": pts})
    return {
        "schemaVersion": 1,
        "caseRevision": ids["revision"],
        "rubricRevision": ids["rubricRevision"],
        "dimensions": [{"id": d, "weight": w} for d, w in sit.dims],
        "main": main_cells,
        "evidence": evidence_cells,
        "followup": {"type": "new_information",
                     "responses": [{"responseId": r["id"], "quality": qualities[r["id"]]} for r in followup["responses"]]},
    }


# ---------------------------------------------------------------------------
# Disclosure self-check (mirror of the validator's 6-word overlap rule)
# ---------------------------------------------------------------------------

_NON_PROSE_KEYS = {"evidenceId", "kind", "timestamp", "caseRevision", "schemaVersion", "editionId", "id"}


def _brief_texts(brief: dict[str, Any]) -> list[str]:
    texts = [brief["title"], brief["focus"]]
    for key in ("facts", "actions", "qualifiers", "evidence", "confidence"):
        for item in brief[key]:
            texts.append(item["text"] if key == "facts" else item["label"])
    return texts


def _walk_prose(node: Any, path: str = ""):
    """Yield (container, key, text) for every prose string, skipping the validator's non-prose keys."""
    if isinstance(node, dict):
        for key, value in node.items():
            if key in _NON_PROSE_KEYS:
                continue
            if isinstance(value, str):
                yield node, key, value
            else:
                yield from _walk_prose(value, f"{path}.{key}")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            if isinstance(value, str):
                yield node, index, value
            else:
                yield from _walk_prose(value, f"{path}[{index}]")


def brief_shingle_set(brief: dict[str, Any]) -> set[str]:
    return {gram for text in _brief_texts(brief) for gram in shingles(text)}


def disclosure_overlaps(case: dict[str, Any]) -> list[str]:
    """Fields of the follow-up/reveal that share a 6-word sequence with the brief (empty = passes)."""
    banned = brief_shingle_set(case["brief"])
    leaks = []
    for section in ("followup", "reveal"):
        for container, key, text in _walk_prose(case[section]):
            hit = next((g for g in shingles(text) if g in banned), None)
            if hit:
                leaks.append(f"{section}.{key}: {hit}")
    return leaks


def _enforce_no_overlap(case: dict[str, Any]) -> list[str]:
    banned = brief_shingle_set(case["brief"])
    adjusted: list[str] = []
    for section in ("followup", "reveal"):
        for container, key, text in list(_walk_prose(case[section])):
            new, changed = break_overlap(text, banned)
            if changed:
                container[key] = new
                adjusted.append(f"{section}.{key}")
    return adjusted


# ---------------------------------------------------------------------------
# Editorial
# ---------------------------------------------------------------------------


def _read_manifest(source_id: str) -> dict[str, Any] | None:
    try:
        path = paths.manifests_dir() / f"{source_id}.json"
        return read_json(path) if path.exists() else None
    except Exception:  # noqa: BLE001 - provenance lookup is best effort
        return None


def demo_sha256(candidate: dict[str, Any], manifest: dict[str, Any] | None) -> str:
    for source in (candidate, candidate.get("groundTruth") or {}):
        value = source.get("demoSha256")
        if value:
            return str(value)
    if manifest and manifest.get("demo", {}).get("sha256"):
        return str(manifest["demo"]["sha256"])
    try:  # the parsed match carries the demo hash too
        match_path = paths.parsed_dir(candidate["sourceId"]) / "match.json"
        if match_path.exists():
            return str(read_json(match_path).get("demoSha256", "unknown"))
    except Exception:  # noqa: BLE001
        pass
    return "unknown"


def build_editorial(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str], main: MainPrior,
                    evidence: list[Signal], qualities: dict[str, int], cls_text: str, issues: list[str]) -> dict[str, Any]:
    manifest = _read_manifest(candidate["sourceId"])
    sha = demo_sha256(candidate, manifest)
    embedded = (candidate.get("groundTruth") or {}).get("source") or {}
    lane = (manifest or {}).get("rights", {}).get("contentLane") or embedded.get("contentLane") or "unknown (manifest not found)"
    reference = {
        "label": "Demo source (demo_source)",
        "detail": (
            f"kind=demo_source; sourceId={candidate['sourceId']}; candidateId={candidate['candidateId']}; "
            f"map={candidate.get('map')}; round={candidate.get('round')}; decisionTick={candidate.get('decisionTick')}; "
            f"decisionT={candidate.get('decisionT')}s; perspective={candidate.get('perspective')}; "
            f"category={candidate.get('category')}; demoSha256={sha}"
        ),
        "kind": "source",
    }
    score = candidate.get("score") or {}
    notes = [
        PROPOSED_RUBRIC_NOTE,
        "",
        "LANE: demo-grounded SYNTHETIC. The situation is inspired by a decision point in a real demo (see references) but the case "
        "does not claim to reproduce the match and contains no player names, Steam IDs, team names or player ids. "
        f"Content lane recorded on the source manifest: {lane}.",
        "The brief, evidence and actions use only candidate.playerKnown (plus map, perspective and category). The follow-up uses only "
        "candidate.followUp. Ground truth and the actual line appear only in the reveal. The historical line is shown for comparison "
        "and is NOT treated as the correct answer.",
        f"Candidate: {candidate['candidateId']} (score {score.get('total')}, category {candidate.get('category')}, "
        f"template family {sit.id}). Summary: {scrub(str(candidate.get('summary', '')))}",
        "",
        "PRIOR TABLE (every rubric value below is derivable from these rules and the player-known features):",
        *main.explain,
        *(f"normalisation: {line}" for line in main.normalised),
        f"follow-up: {cls_text}; qualities " + ", ".join(f"{k}={v}" for k, v in sorted(qualities.items())),
        *(f"  {line}" for line in [
            f"evidence pairs: points = clamp(round(20 * (w_a + w_b) / (w_top1 + w_top2)), 3, 20) with per-signal weights from the "
            f"situation table and per-action overrides; signals: " + ", ".join(f"{s.id}({s.cls})" for s in evidence)]),
        f"Order of actions/qualifiers/responses is a deterministic hash of the candidate id; the top-ranked action is never first.",
    ]
    return {
        "status": "draft",
        "revision": ids["revision"],
        "rubricRevision": ids["rubricRevision"],
        "author": AUTHOR,
        "reviewers": [],
        "references": [reference],
        "knownIssues": issues,
        "notes": "\n".join(notes),
    }


# ---------------------------------------------------------------------------
# Public entry: build_case
# ---------------------------------------------------------------------------


def build_case(candidate: dict[str, Any], *, case_id: str | None = None) -> dict[str, Any]:
    cid = make_case_id(candidate, case_id)
    ids = derived_ids(cid)
    f = extract_features(candidate)
    sit = SITUATIONS[f.situation]
    main = compute_main_prior(sit, f)
    evidence = choose_evidence(sit, f)
    actions_ordered = order_actions(main.actions, candidate["candidateId"])

    brief, brief_issues = build_brief(candidate, f, sit, ids, main, evidence, actions_ordered)
    followup, qualities, cls_key, cls_text, followup_issues = build_followup(
        candidate, f, sit, ids, {fact["id"] for fact in brief["facts"]})
    reveal, reveal_issues = build_reveal(candidate, f, sit, ids, main, evidence, qualities, cls_key)
    rubric = build_rubric(sit, ids, main, brief, evidence, qualities, followup)

    issues: list[str] = [scrub(str(note)) for note in candidate.get("reviewNotes") or []]
    issues += brief_issues + followup_issues + reveal_issues
    issues += [
        "The option set (actions, qualifiers, follow-up responses) is a template for this situation family, not derived from the demo; "
        "a reviewer must confirm every option is playable on this map at this moment and that no defensible line is missing.",
        "The debrief reasoning (whyItWorks, cost, assumption, breaksWhen, strongestAlternative, counterfactual, evidence explanations, "
        "principle) is templated per situation family and needs human tactical review.",
        "Rubric ratings, evidence points and follow-up qualities are heuristic priors (see editorial.notes), not tactical judgements; "
        "time thresholds (defuse duration + 7 s, 25 s comfortable) are unreviewed assumptions.",
        "The reveal continuation is machine-rendered from demo events; check it against the demo before any review.",
        f"publicMetadata.case_number ({PLACEHOLDER_CASE_NUMBER}) and edition_date_utc ({PLACEHOLDER_EDITION_DATE}) are placeholders to set at scheduling.",
        "editorial.references cannot carry a demo_source kind (the editorial schema allows only background_reading or source); "
        "the demo source is recorded as kind 'source' with a structured detail string.",
    ]
    if len(main.actions) and sum(1 for a in main.actions if a.best_quality >= 70) < 2:
        issues.append("Under the proposed priors only one action reaches a defensible line (>= 70); the decision may not be a real dilemma here.")
    issues.extend(f"Prior normalisation: {line}" for line in main.normalised)

    case: dict[str, Any] = {
        "caseId": cid,
        "origin": "synthetic",
        "editorial": None,  # filled after the disclosure pass so knownIssues can mention adjustments
        "edition": {
            "editionId": ids["editionId"],
            "releaseAt": None,
            "officialEndAt": None,
            "graceEndAt": None,
            "publicMetadata": {
                "case_number": PLACEHOLDER_CASE_NUMBER,
                "edition_date_utc": PLACEHOLDER_EDITION_DATE,
                "estimated_minutes": 6,
                "focus": sit.focus,
                "origin_label": ORIGIN_LABEL,
            },
        },
        "brief": brief,
        "followup": followup,
        "reveal": reveal,
        "rubric": rubric,
    }
    adjusted = _enforce_no_overlap(case)
    if adjusted:
        issues.append("Wording of these follow-up/reveal fields was auto-adjusted to avoid a 6-word overlap with the brief; "
                      "review for readability: " + ", ".join(adjusted))
    case["editorial"] = build_editorial(candidate, f, sit, ids, main, evidence, qualities, cls_text, issues)
    # Re-order keys so the file reads editorial-first like the existing cases.
    return {key: case[key] for key in ("caseId", "origin", "editorial", "edition", "brief", "followup", "reveal", "rubric")}


def player_facing_text(case: dict[str, Any]) -> list[str]:
    """Every string a player can see (brief, follow-up, reveal, public metadata)."""
    texts: list[str] = []
    for section in ("brief", "followup", "reveal"):
        texts += [text for _, _, text in _walk_prose(case[section])]
    texts += [str(v) for v in case["edition"]["publicMetadata"].values()]
    return texts


def identity_leaks(case: dict[str, Any]) -> list[str]:
    return [text for text in player_facing_text(case) if has_identity(text)]


# ---------------------------------------------------------------------------
# draft_case: write + validate + review
# ---------------------------------------------------------------------------


def _existing_status(path: Path) -> str | None:
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("editorial", {}).get("status")
    except Exception:  # noqa: BLE001
        return None


def draft_case(candidate_path: Path, *, case_id: str | None = None, out_dir: Path | None = None,
               validate: bool = True, overwrite: bool = False) -> tuple[Path, dict[str, Any]]:
    from .review import write_review
    from .validate_run import run_validator

    candidate_path = Path(candidate_path)
    candidate = read_json(candidate_path)
    case = build_case(candidate, case_id=case_id)
    target_dir = Path(out_dir) if out_dir is not None else paths.cases_dir()
    target = target_dir / f"{case['caseId']}.json"
    if target.exists():
        status = _existing_status(target)
        if status != "draft":
            raise DraftRefused(f"{target} exists with status {status!r}; only files whose status is 'draft' can be regenerated.")
        if not overwrite:
            raise DraftRefused(f"{target} already exists; pass overwrite=True to replace this draft.")
    target_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(case, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    if validate:
        report = run_validator(case["caseId"], target)
    else:
        report = {"caseId": case["caseId"], "path": str(target), "validatorExitCode": None,
                  "errors": [], "warnings": [], "publishable": False, "validated": False}
    write_review(candidate_path, candidate, case, report)
    return target, report
