"""Editorial bridge: mined Candidate -> Roundcraft case DRAFT JSON (content/cases/<caseId>.json).

Hard rules (see tools/case-miner README and AGENTS.md):
  * the output is always status "draft", origin "synthetic", with the exact synthetic origin label;
  * the BRIEF and its evidence/actions use only candidate.playerKnown (+ map/perspective/category);
  * the FOLLOW-UP uses only candidate.followUp; the REVEAL may use groundTruth and actualLine;
  * the rubric is a PROPOSAL from documented heuristics (templates.py / priors.py), never tactical truth;
  * no player names, Steam IDs, team names or pids in any player-facing text.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .. import paths
from ..model import read_json
from .features import Features, extract_features
from .priors import (
    ActionPrior,
    MainPrior,
    Signal,
    choose_evidence,
    compute_main_prior,
    evidence_points,
    FollowupMatrix,
    followup_class,
    followup_matrix,
    generic_elapsed,
    seen_groups,
    order_actions,
    order_qualifiers,
    order_responses,
    response_id,
    stable_hash,
)
from .templates import SITUATIONS, Situation, fill
from .text import (
    break_overlap,
    clock_label,
    fix_weapon_articles,
    has_identity,
    map_display,
    map_slug,
    pretty_place,
    scrub,
    seconds_phrase,
    shingles,
    slug,
    truncate,
)
from .timeline import decisive_summary, readable_actual_line, render_outcome, render_timeline, weapon_display

ORIGIN_LABEL = "Synthetic scenario — editorial tactical analysis."
PROPOSED_RUBRIC_NOTE = (
    "PROPOSED RUBRIC — generated by heuristics from category templates; "
    "requires human tactical review before technically_validated."
)
AUTHOR = "roundcraft-miner (generated draft)"
CONFIDENCE = [
    {"id": "guessing", "label": "Guessing"},
    {"id": "leaning", "label": "Leaning"},
    {"id": "fairly_sure", "label": "Fairly sure"},
    {"id": "strong_read", "label": "Strong read"},
]
FACT_STATUSES = ("confirmed", "last_seen", "inferred", "unknown")
MAX_FACTS = 14
PLACEHOLDER_CASE_NUMBER = 900
PLACEHOLDER_EDITION_DATE = "2099-01-01"
CASE_ID_MAX = 75  # leaves room for the cr_/rr_/ed_ prefixes inside the 80-char identifier limit


class DraftRefused(RuntimeError):
    """Raised when writing a draft would overwrite something it must not."""


# ---------------------------------------------------------------------------
# Identifiers
# ---------------------------------------------------------------------------


def make_case_id(candidate: dict[str, Any], case_id: str | None = None) -> str:
    if case_id:
        cid = slug(case_id, max_len=CASE_ID_MAX)
        if cid != case_id:
            raise ValueError(f"case id {case_id!r} must match ^[a-z0-9_]+$ (max {CASE_ID_MAX} chars)")
        return cid
    short = slug(str(candidate["candidateId"]).removeprefix("cand_"), max_len=8)[:6]
    category = slug(candidate.get("category", "case"), max_len=28)
    return f"case_{map_slug(candidate.get('map', 'map'))}_{category}_{short}"[:CASE_ID_MAX].rstrip("_")


def derived_ids(case_id: str) -> dict[str, str]:
    stem = case_id.removeprefix("case_")
    return {"revision": f"cr_{stem}", "rubricRevision": f"rr_{stem}", "editionId": f"ed_{stem}"}


def _ident(text: str, taken: set[str], fallback: str) -> str:
    base = slug(text, max_len=60) if text else fallback
    candidate, n = base, 2
    while candidate in taken:
        candidate = f"{base}_{n}"
        n += 1
    taken.add(candidate)
    return candidate


# ---------------------------------------------------------------------------
# Brief (player-known only)
# ---------------------------------------------------------------------------

_FACT_CLASS_KEYWORDS: tuple[tuple[int, tuple[str, ...]], ...] = (
    (0, ("clock", "timer", "bomb", "time")),
    (1, ("alive", "players", "head")),
    (2, ("utility", "smoke", "flash", "grenade", "molotov", "he_")),
    (3, ("seen", "spotted", "sight", "heard")),
    (4, ("unknown", "unaccounted", "hidden")),
)


def _fact_class(fact: dict[str, Any]) -> int:
    hay = f"{fact.get('id', '')} {fact.get('text', '')}".lower()
    for cls, words in _FACT_CLASS_KEYWORDS:
        if any(word in hay for word in words):
            return cls
    if fact.get("status") in ("last_seen", "confirmed"):
        return 3
    return 5


def _plural(n: int, word: str, plural: str | None = None) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {plural or word + 's'}"


def _utility_sentence(f: Features) -> str | None:
    parts = []
    for kind, one, many in (("smoke", "smoke", "smokes"), ("flash", "flash", "flashes"),
                            ("he", "HE grenade", "HE grenades"), ("molotov", "molotov", "molotovs"),
                            ("decoy", "decoy", "decoys")):
        count = f.util.get(kind, 0)
        if count:
            parts.append(_plural(count, one, many))
    if not parts:
        return None
    joined = parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]
    return f"Your team still holds {joined}."


def build_facts(candidate: dict[str, Any], f: Features) -> tuple[list[dict[str, str]], list[str]]:
    issues: list[str] = []
    view = candidate["playerKnown"]
    taken: set[str] = set()
    mined: list[tuple[int, int, dict[str, str]]] = []
    for index, raw in enumerate(view.get("facts") or []):
        status = raw.get("status")
        if status not in FACT_STATUSES:
            issues.append(f"Mined fact {raw.get('id')!r} had an unrecognised status {status!r}; treated as 'unknown'.")
            status = "unknown"
        text = fix_weapon_articles(scrub(str(raw.get("text", "")).strip()))
        basis = re.sub(r"\brounds? \d+(?:, \d+)*", "recent rounds", scrub(str(raw.get("basis", "")).strip()))
        if status == "inferred" and basis and "basis" not in text.lower() and len(text) + len(basis) < 470:
            text = f"{text.rstrip('.')}. Basis: {basis.rstrip('.')}."
        if not text:
            continue
        mined.append((_fact_class(raw), index, {"id": _ident(str(raw.get("id", "")), taken, f"fact_{index + 1}"),
                                                "status": status, "text": truncate(text, 500)}))
        if status == "last_seen" and not any(ch.isdigit() for ch in text) and "ago" not in text.lower():
            issues.append(f"Fact {mined[-1][2]['id']!r} is last_seen but its text states no age.")

    derived: list[tuple[int, dict[str, str]]] = []
    classes = {cls for cls, _, _ in mined}
    perspective_fact = {"id": _ident("perspective", taken, "perspective"), "status": "confirmed",
                        "text": f"You play the {f.perspective} side on {map_display(f.map_name)}."}
    if 0 not in classes and f.time_left is not None:
        if f.time_kind == "bomb":
            site = f" on site {f.bomb_site}" if f.bomb_site else ""
            text = f"The bomb is planted{site}. About {seconds_phrase(f.time_left)} are left before it explodes."
            fid = "bomb_timer"
        else:
            text = f"About {seconds_phrase(f.time_left)} are left on the round clock."
            fid = "round_clock"
        derived.append((0, {"id": _ident(fid, taken, fid), "status": "confirmed", "text": text}))
    if 1 not in classes:
        derived.append((1, {"id": _ident("alive_count", taken, "alive_count"), "status": "confirmed",
                            "text": f"Your team has {f.own_alive} players alive and the opposing team has {f.enemy_alive}."}))
    if 2 not in classes:
        sentence = _utility_sentence(f)
        if sentence:
            derived.append((2, {"id": _ident("own_utility", taken, "own_utility"), "status": "confirmed", "text": sentence}))
    if f.perspective == "CT" and f.own_alive > 0:
        # Kits are visible on the scoreboard to teammates, so this is known to the deciding team.
        kit_text = ("No one on your team carries a defuse kit." if f.own_kit == 0 else
                    f"{f.own_kit} of your {f.own_alive} alive players {'carries' if f.own_kit == 1 else 'carry'} a defuse kit.")
        derived.append((2, {"id": _ident("defuse_kits", taken, "defuse_kits"), "status": "confirmed", "text": kit_text}))
    if 4 not in classes and f.unknown_enemies > 0 and not any(m[2]["status"] == "unknown" for m in mined):
        derived.append((4, {"id": _ident("unknown_positions", taken, "unknown_positions"), "status": "unknown",
                            "text": f"{_plural(f.unknown_enemies, f.enemy_noun)} cannot currently be placed."}))

    # mined facts keep their source order inside a class; derived facts sort ahead of mined ones of the same class
    keyed = [(cls, 0, i, fact) for i, (cls, fact) in enumerate(derived)] + [(cls, 1, idx, fact) for cls, idx, fact in mined]
    facts = [perspective_fact] + [item[3] for item in sorted(keyed, key=lambda item: item[:3])]
    if len(facts) > MAX_FACTS:
        issues.append(f"Brief facts were capped at {MAX_FACTS} by priority (clock/bomb, alive counts, utility, sightings, unknowns); "
                      f"{len(facts) - MAX_FACTS} lower-priority fact(s) were dropped.")
        facts = facts[:MAX_FACTS]
    if not any(fact["status"] in ("inferred", "unknown") for fact in facts):
        issues.append("No fact is marked inferred or unknown; the brief presents nothing as uncertain.")
    return facts, issues


def specific_title(sit: Situation, f: Features) -> str:
    """A title that names the actual situation, e.g. '2v2 retake at A on Mirage'."""
    game = f"{f.own_alive}v{f.enemy_alive}"
    where = map_display(f.map_name)
    site = f" at {f.bomb_site}" if f.bomb_site else ""
    seconds = f"{f.time_left:.0f} s" if f.time_left is not None else None
    if sit.id == "retake":
        return f"{game} retake{site} on {where}"
    if sit.id == "post_plant_hold":
        return f"{game} post-plant{site} on {where}"
    if sit.id == "execute_or_default" and seconds and f.time_left is not None and f.time_left <= 20:
        return f"Plant or save: {game} with {seconds} left on {where}"
    if sit.id == "execute_or_default" and seconds:
        ground = " and the bomb on the ground" if f.bomb_status == "dropped" else " and no plant"
        return f"{game} with {seconds} left{ground} on {where}"
    if sit.id == "execute_or_default":
        return f"{game} mid-round read as the attackers on {where}"
    if sit.id == "hold_or_rotate":
        return f"{game} hold or rotate as the defenders on {where}"
    return sit.title.format(map=where)


FOCUS_MAX = 80  # publicMetadata.focus limit


def focus_for(sit: Situation, f: Features) -> str:
    """A focus line that matches the situation actually presented (variants of the family default)."""
    late = f.time_left is not None
    if sit.id == "execute_or_default" and late and f.time <= 20:
        focus = "Trying to plant with the clock nearly gone versus saving the weapons"
    elif sit.id == "execute_or_default" and late and f.time <= 45:
        focus = "Committing to a plant with the round clock running short"
    elif sit.id == "retake" and f.time < f.t_low:
        focus = "Whether a retake can still finish before the bomb explodes"
    elif sit.id == "post_plant_hold" and f.time < 12:
        focus = "Staying out of contact while the bomb timer runs out"
    else:
        focus = sit.focus
    return truncate(focus, FOCUS_MAX)


def build_brief(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str],
                main: MainPrior, evidence: list[Signal], actions_ordered: list[ActionPrior]) -> tuple[dict[str, Any], list[str]]:
    facts, issues = build_facts(candidate, f)
    qualifiers: list[dict[str, str]] = []
    actions: list[dict[str, Any]] = []
    for action in actions_ordered:
        quals = order_qualifiers(action.qualifiers, candidate["candidateId"], action.template.id)
        for q in quals:
            qualifiers.append({"id": q.id, "label": q.label})
        actions.append({"id": action.template.id, "label": truncate(scrub(action.label), 120),
                        "qualifierIds": [q.id for q in quals]})
    brief = {
        "schemaVersion": 1,
        "editionId": ids["editionId"],
        "caseRevision": ids["revision"],
        "title": specific_title(sit, f),
        "focus": focus_for(sit, f),
        "origin": "synthetic",
        "facts": facts,
        "actions": actions,
        "qualifiers": qualifiers,
        "evidence": [{"id": s.id, "label": scrub(s.label)} for s in evidence],
        "confidence": [dict(c) for c in CONFIDENCE],
    }
    return brief, issues


# ---------------------------------------------------------------------------
# Follow-up (candidate.followUp only)
# ---------------------------------------------------------------------------

_HEADINGS = (  # first match wins: "utility_seen" must read as utility, not as a sighting
    ("utility", "New enemy utility"),
    ("plant", "The bomb is planted"),
    ("defus", "A defuse begins"),
    ("kill", "A player is eliminated"),
    ("elimin", "A player is eliminated"),
    ("spot", "A new sighting"),
    ("seen", "A new sighting"),
    ("heard", "A new sound"),
    ("sound", "A new sound"),
)


def _heading(kind: str) -> str:
    kind = (kind or "").lower()
    for key, heading in _HEADINGS:
        if key in kind:
            return heading
    return "The round moves on"


NO_FOLLOWUP_ISSUE = ("Follow-up must be authored: the first change after the decision in the source round was the team's own action.")
FOLLOWUP_MATRIX_ISSUE = (
    "Follow-up qualities are a proposed matrix, one cell per locked main action and line now: the value of the line now after the "
    "update, minus a switching cost (10 within the same posture, 20 one step, 30 between passive and active). A reviewer should "
    "check each row: when staying with the locked line is coherent, when changing is justified, and whether the new information "
    "really supports a reversal."
)
SHORT_REACTION_SECONDS = 2.0


def followup_caveats(follow: dict[str, Any] | None) -> list[str]:
    """Known issues about how the mined follow-up came about (fields are absent on older candidates)."""
    if not follow:
        return []
    lines: list[str] = []
    if follow.get("dependsOnOwnMovement") is True:
        lines.append(
            "Follow-up depends on the team's own movement: the new information only arrived because the deciding team moved, so a "
            "player who chose a different main call might not have received it. Confirm it is fair for every main line or author a different one."
        )
    window = follow.get("reactionWindowSeconds")
    if isinstance(window, (int, float)) and not isinstance(window, bool) and window < SHORT_REACTION_SECONDS:
        lines.append(
            f"Follow-up reaction window is only {window:g} s: in the source round the situation changed again almost at once, so the "
            "responses may not be meaningfully playable. Confirm the window is long enough or author a different follow-up."
        )
    return lines


def build_followup(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str], main: MainPrior,
                   brief_fact_ids: set[str]) -> tuple[dict[str, Any], FollowupMatrix, str, str, list[str]]:
    issues: list[str] = []
    follow = candidate.get("followUp")
    cls, cls_text, after = followup_class(sit, f, follow, candidate)
    matrix = followup_matrix(sit, main, f, after)
    responses = order_responses([a.template.id for a in main.actions], matrix.value_after, candidate["candidateId"])
    updates: list[dict[str, str]] = []
    taken: set[str] = set()
    if follow is None:
        issues.append(NO_FOLLOWUP_ISSUE)
        heading = "The clock runs down"
        elapsed = generic_elapsed(f)
        updates.append({"id": "no_new_contact", "status": "unchanged", "text": "No new position has been confirmed."})
        taken.add("no_new_contact")
        if elapsed is None:
            stimulus = "Time passes without new contact."
        else:
            noun = "bomb timer" if f.time_kind == "bomb" else "round clock"
            remaining = max(0, int(round(f.time - elapsed)))
            stimulus = f"About {elapsed} seconds pass without new contact; the {noun} now shows {remaining} s."
            updates.append({"id": _ident("clock_now", taken, "clock_now"), "status": "changed",
                            "text": f"About {seconds_phrase(remaining)} now remain on the {noun}."})
    else:
        issues.extend(followup_caveats(follow))
        heading = _heading(follow.get("kind", ""))
        delta = follow.get("t", 0) - candidate.get("decisionT", 0)
        summary = scrub(str(follow.get("summary", "")).strip())
        stimulus = (f"About {seconds_phrase(delta)} later, {summary[:1].lower()}{summary[1:]}"
                    if delta >= 1 and summary else summary)
        for index, fact in enumerate(follow.get("newFacts") or []):
            status = fact.get("status")
            text = scrub(str(fact.get("text", "")).strip())
            if not text:
                continue
            label = {"last_seen": "last seen", "inferred": "inferred", "unknown": "unknown"}.get(status or "")
            if label and label not in text.lower():
                text = f"{label.capitalize()}: {text}"
            uid = _ident(str(fact.get("id", "")), taken, f"update_{index + 1}")
            updates.append({"id": uid, "status": "changed" if fact.get("id") in brief_fact_ids else "new",
                            "text": truncate(text, 500)})
        mined_ids = " ".join(str(fact.get("id", "")) for fact in follow.get("newFacts") or [])
        mined_text = " ".join(update["text"].lower() for update in updates)
        if follow is not None:
            if after.time_left is not None and not re.search(r"\b(bomb_planted|clock)", mined_ids) and "remain on the" not in mined_text:
                noun = "bomb timer" if after.time_kind == "bomb" else "round clock"
                updates.append({"id": _ident("clock_now", taken, "clock_now"), "status": "changed",
                                "text": f"About {seconds_phrase(after.time_left)} now remain on the {noun}."})
            if (after.own_alive, after.enemy_alive) != (f.own_alive, f.enemy_alive) and "alive_" not in mined_ids:
                updates.append({"id": _ident("alive_now", taken, "alive_now"), "status": "changed",
                                "text": f"Your team now has {after.own_alive} players alive and the opposing team has {after.enemy_alive}."})
        if not updates:
            updates.append({"id": "change", "status": "new", "text": stimulus or "The situation has changed."})
        if not stimulus:
            stimulus = "The situation has changed."
    followup = {
        "schemaVersion": 1,
        "caseRevision": ids["revision"],
        "type": "new_information",
        "heading": heading,
        "stimulus": truncate(stimulus, 800),
        "updates": updates[:20],
        "responses": [{"id": response_id(action_id), "label": matrix.label(action_id)} for action_id in responses],
    }
    return followup, matrix, cls, cls_text, issues


# ---------------------------------------------------------------------------
# Reveal (groundTruth / actualLine allowed)
# ---------------------------------------------------------------------------


_HISTORICAL_PREFIX = re.compile(r"^HISTORICAL LINE \([^)]*\)\.?\s*")


def _lower_first(text: str) -> str:
    """Lower-case the first word of a sentence unless it is an acronym or a side name (CT, T)."""
    first = text.split(" ", 1)[0].strip(",.:;")
    if not text or first in ("T", "CT") or (len(first) > 1 and first.isupper()):
        return text
    return text[0].lower() + text[1:]


_NUMBER_WORDS = {0: "no", 1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten"}


def _count(n: int, one: str, many: str | None = None) -> str:
    word = _NUMBER_WORDS.get(n, str(n))
    return f"{word} {one if n == 1 else (many or one + 's')}"


def _own_utility_sentence(f: Features) -> str:
    kinds = (("smoke", "smoke", "smokes"), ("flash", "flash", "flashes"), ("he", "HE grenade", "HE grenades"),
             ("molotov", "molotov", "molotovs"), ("decoy", "decoy", "decoys"))
    present = [_count(f.util.get(k, 0), one, many) for k, one, many in kinds if f.util.get(k, 0)]
    if not present:
        return "The team had no utility left."
    absent = [many for k, _, many in kinds[:4] if not f.util.get(k, 0)]
    have = present[0] if len(present) == 1 else ", ".join(present[:-1]) + " and " + present[-1]
    sentence = f"The team had {have}"
    if absent:
        sentence += " and no " + (absent[0] if len(absent) == 1 else ", ".join(absent[:-1]) + " or " + absent[-1])
    return sentence + "."


def _kit_sentence(f: Features) -> str:
    if f.own_kit == 0:
        return f"No one carried a defuse kit, so a defuse needed about {seconds_phrase(f.defuse_needed)}."
    if f.own_kit >= f.own_alive:
        who = "Both players carried defuse kits" if f.own_alive == 2 else f"All {f.own_alive} players carried defuse kits"
        return f"{who}, so a defuse needed about {seconds_phrase(5)}."
    return (f"{_count(f.own_kit, 'player')} of {f.own_alive} carried a defuse kit, so a defuse took about {seconds_phrase(5)} for a kit "
            f"holder and about {seconds_phrase(10)} for anyone else.")


def _weapon_name(raw: str) -> str:
    shown = weapon_display(raw)
    return re.sub(r"^(?:an?|the) ", "", shown) if shown != raw.lower().replace("_", " ") else raw


def _own_players(view: dict[str, Any]) -> list[dict[str, Any]]:
    return [p for p in view.get("own") or [] if p.get("alive", True)]


def _evidence_sentence(s: Signal, f: Features, view: dict[str, Any]) -> str:
    """One factual sentence for an evidence option, grounded only in the player-known view."""
    noun = f.enemy_noun
    if s.id == "side_and_map":
        return f"You played the {f.perspective} side on {map_display(f.map_name)}."
    if s.id == "own_health":
        hp = [int(p["hp"]) for p in _own_players(view) if isinstance(p.get("hp"), (int, float))]
        if hp:
            listed = " and ".join(f"{h}" for h in hp) if len(hp) <= 2 else ", ".join(map(str, hp[:-1])) + f" and {hp[-1]}"
            return f"The players had {listed} health."
        return "Each player's health and armour were visible to the team."
    if s.cls == "bomb_timer" and f.time_left is not None:
        return f"The bomb timer stood near {seconds_phrase(f.time_left)}."
    if s.cls == "clock" and f.time_left is not None:
        return f"The round clock stood near {seconds_phrase(f.time_left)}."
    if s.cls == "alive_count":
        return f"It was {f.own_alive} players against {f.enemy_alive}."
    if s.cls == "own_utility":
        return _own_utility_sentence(f)
    if s.cls == "defuse_kit":
        return _kit_sentence(f)
    if s.cls == "enemy_seen":
        groups = seen_groups(f)
        index = int(s.id.rsplit("_", 1)[-1]) - 1
        if 0 <= index < len(groups):
            enemy, count = groups[index]
            who = _count(count, noun)
            kind = "confirmed" if enemy.status == "confirmed" else "last-seen"
            age = ("current" if enemy.age is None or enemy.age < 1.5 else f"about {seconds_phrase(enemy.age)} old")
            return f"The {kind} position of {who} in {enemy.place} was {age}."
    if s.cls == "enemy_unknown":
        return f"{_count(f.unknown_enemies, noun).capitalize()} could not be placed."
    if s.cls == "bomb_location":
        where = f"at {f.bomb_site}" if f.bomb_site else (f"in {f.bomb_place}" if f.bomb_place else "on site")
        return f"The bomb was planted {where}."
    if s.cls == "enemy_utility" and f.observed_enemy_utility:
        names = {"smoke": "smoke", "flash": "flash", "he": "HE grenade", "molotov": "molotov", "decoy": "decoy"}
        counts: dict[str, int] = {}
        for kind in f.observed_enemy_utility:
            counts[kind] = counts.get(kind, 0) + 1
        parts = [_count(n, names.get(k, k), names.get(k, k) + ("es" if k == "flash" else "s")) for k, n in sorted(counts.items())]
        return f"The {noun}s had already used {' and '.join(parts) if len(parts) < 3 else ', '.join(parts[:-1]) + ' and ' + parts[-1]}."
    if s.cls == "own_positions":
        places: dict[str, int] = {}
        for p in _own_players(view):
            place = pretty_place(p.get("place"))
            if place:
                places[place] = places.get(place, 0) + 1
        if places:
            return "The team's players stood as follows: " + ", ".join(f"{_NUMBER_WORDS.get(n, n)} in {pl}" for pl, n in places.items()) + "."
    if s.cls == "own_loadout":
        weapons: dict[str, int] = {}
        for p in _own_players(view):
            raw = p.get("primary") or p.get("activeWeapon")
            if raw:
                weapons[_weapon_name(str(raw))] = weapons.get(_weapon_name(str(raw)), 0) + 1
        if weapons:
            listed = ", ".join(_count(n, w) for w, n in weapons.items())
            armoured = sum(1 for p in _own_players(view) if (p.get("armor") or 0) > 0)
            return f"The team carried {listed}; {armoured} of {len(_own_players(view))} wore armour."
    return "This was part of what the team could see at the decision point."


def _followup_review(matrix: FollowupMatrix, cls_key: str) -> str:
    """Public explanation of how the follow-up was scored; the same text is shown whatever the player chose."""
    lead = matrix.best_before
    lead_answer = max(matrix.value_after, key=lambda now: (matrix.cells[(lead, now)], now == lead))
    opening = ("No decisive new information arrived, so the question was whether the line still held as the clock ran down. "
               if cls_key == "no_followup" else "")
    if lead_answer == lead:
        middle = (f"The update did not overturn the strongest line, so staying with it scored best "
                  f"(\"{matrix.label(lead)}\").")
    else:
        middle = (f"The update made another line stronger, so even a sound first call did best to move: "
                  f"\"{matrix.label(lead_answer)}\".")
    return (f"{opening}The follow-up was judged against the line you locked. {middle} Changing course earned the value of the new "
            "line less the time and position a switch costs, so correcting a weaker call still scored well, while abandoning a "
            "sound one or holding on to a weak one did not.")


def build_reveal(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str], main: MainPrior,
                 evidence: list[Signal], matrix: FollowupMatrix, cls_key: str) -> tuple[dict[str, Any], list[str]]:
    issues: list[str] = []
    events, timeline_issues, raw_actions = render_timeline(candidate, f)
    issues.extend(timeline_issues)
    lead, second = main.actions[0], main.actions[1]
    follow = candidate.get("followUp")
    actual = _HISTORICAL_PREFIX.sub("", scrub(str(candidate.get("actualLine", "")).strip()))
    if actual:
        extra = "" if "defus" in actual.lower() else decisive_summary(candidate)
        round_action = f"In the source round, {_lower_first(readable_actual_line(actual, candidate, extra))}"
    else:
        round_action = "The source round's line was not recorded for this decision point."
        issues.append("candidate.actualLine is empty; the comparison has no historical line.")
    if follow:
        material = f"The information that arrived after the decision: {scrub(str(follow.get('summary', '')).strip())}"
    else:
        material = "No separate new information is recorded between the decision point and the outcome."
    outcome = render_outcome(candidate, f)
    if raw_actions:
        round_followup = "After the decision the source round continued: " + " ".join(raw_actions[:2])
        if outcome:
            round_followup = f"{round_followup} {outcome}"
    else:
        round_followup = "No further events are recorded after the decision point." + (f" {outcome}" if outcome else "")

    why = fill(lead.template.why, f)
    if f.time_left is not None:
        why += (f" Here, {f.own_alive} players faced {f.enemy_alive} with about {seconds_phrase(f.time_left)} left.")
    else:
        why += f" Here, {f.own_alive} players faced {f.enemy_alive}."
    alt_text = f"The closest alternative was {fill(second.template.alt, f)}."

    weights = {s.id: lead.template.evidence_weights.get(s.cls, sit.evidence_weights.get(s.cls, 1)) for s in evidence}
    ordered_evidence = sorted(evidence, key=lambda s: (-weights[s.id], s.id))
    review_entries = []
    for s in ordered_evidence:  # one entry for EVERY evidence option the player could pick
        note = sit.evidence_notes.get(s.cls, "")
        review_entries.append({"evidenceId": s.id,
                               "explanation": truncate(f"{_evidence_sentence(s, f, candidate['playerKnown'])} {note}".strip(), 1200)})

    followup_review = _followup_review(matrix, cls_key)

    reveal = {
        "schemaVersion": 1,
        "caseRevision": ids["revision"],
        "continuation": {"kind": "authored", "events": events},
        "comparison": {"roundAction": truncate(round_action, 1200), "materialInformation": truncate(material, 1200),
                       "roundFollowup": truncate(round_followup, 1200)},
        "debrief": {
            "whyItWorks": truncate(why, 1200),
            "cost": fill(lead.template.cost, f),
            "assumption": fill(lead.template.assumption, f),
            "breaksWhen": fill(lead.template.breaks, f),
            "evidenceReview": review_entries,
            "followupReview": truncate(followup_review, 1200),
            "strongestAlternative": truncate(alt_text, 1200),
            "counterfactual": {"changedFact": fill(lead.template.cf_fact, f), "effect": fill(lead.template.cf_effect, f)},
            "method": (
                "Synthetic scenario inspired by a decision point in a recorded round. The situation was rebuilt from anonymised "
                "game data, the options and reasoning are editorial, and the source round's line is shown for comparison "
                "only: it is not treated as the correct answer, and this is not a reconstruction of the match."
            ),
            "sources": [{
                "label": "Roundcraft editorial analysis",
                "detail": "Synthetic scenario based on a recorded round. No match, team or player is identified.",
            }],
        },
        "principle": sit.principle,
    }
    return reveal, issues


# ---------------------------------------------------------------------------
# Rubric (heuristic proposal)
# ---------------------------------------------------------------------------


def build_rubric(sit: Situation, ids: dict[str, str], main: MainPrior, brief: dict[str, Any],
                 evidence: list[Signal], matrix: FollowupMatrix, followup: dict[str, Any]) -> dict[str, Any]:
    by_id = {a.template.id: a for a in main.actions}
    dim_ids = [d for d, _ in sit.dims]
    main_cells: list[dict[str, Any]] = []
    evidence_cells: list[dict[str, Any]] = []
    for action in brief["actions"]:
        prior = by_id[action["id"]]
        quals = {q.id: q for q in prior.qualifiers}
        for qid in action["qualifierIds"]:
            q = quals[qid]
            main_cells.append({"actionId": action["id"], "qualifierId": qid,
                               "ratings": {dim_ids[0]: q.ratings[0], dim_ids[1]: q.ratings[1]},
                               "caps": sorted(prior.caps)[:1] if prior.caps else []})
        points = evidence_points(sit, prior.template, evidence)
        for (a, b), pts in sorted(points.items()):
            evidence_cells.append({"actionId": action["id"], "evidenceIds": [a, b], "points": pts})
    return {
        "schemaVersion": 2,
        "caseRevision": ids["revision"],
        "rubricRevision": ids["rubricRevision"],
        "dimensions": [{"id": d, "weight": w} for d, w in sit.dims],
        "main": main_cells,
        "evidence": evidence_cells,
        "followup": {"type": "new_information",
                     "responses": [{"actionId": action["id"], "responseId": response["id"],
                                    "quality": matrix.cells[(action["id"], response["id"].removeprefix("now_"))]}
                                   for action in brief["actions"] for response in followup["responses"]]},
    }


# ---------------------------------------------------------------------------
# Disclosure self-check (mirror of the validator's 6-word overlap rule)
# ---------------------------------------------------------------------------

_NON_PROSE_KEYS = {"evidenceId", "kind", "timestamp", "caseRevision", "schemaVersion", "editionId", "id"}


def _brief_texts(brief: dict[str, Any]) -> list[str]:
    texts = [brief["title"], brief["focus"]]
    for key in ("facts", "actions", "qualifiers", "evidence", "confidence"):
        for item in brief[key]:
            texts.append(item["text"] if key == "facts" else item["label"])
    return texts


def _walk_prose(node: Any, path: str = ""):
    """Yield (container, key, text) for every prose string, skipping the validator's non-prose keys."""
    if isinstance(node, dict):
        for key, value in node.items():
            if key in _NON_PROSE_KEYS:
                continue
            if isinstance(value, str):
                yield node, key, value
            else:
                yield from _walk_prose(value, f"{path}.{key}")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            if isinstance(value, str):
                yield node, index, value
            else:
                yield from _walk_prose(value, f"{path}[{index}]")


def brief_shingle_set(brief: dict[str, Any]) -> set[str]:
    return {gram for text in _brief_texts(brief) for gram in shingles(text)}


def disclosure_overlaps(case: dict[str, Any]) -> list[str]:
    """Fields of the follow-up/reveal that share a 6-word sequence with the brief (empty = passes)."""
    banned = brief_shingle_set(case["brief"])
    leaks = []
    for section in ("followup", "reveal"):
        for container, key, text in _walk_prose(case[section]):
            hit = next((g for g in shingles(text) if g in banned), None)
            if hit:
                leaks.append(f"{section}.{key}: {hit}")
    return leaks


def _enforce_no_overlap(case: dict[str, Any]) -> list[str]:
    banned = brief_shingle_set(case["brief"])
    adjusted: list[str] = []
    for section in ("followup", "reveal"):
        for container, key, text in list(_walk_prose(case[section])):
            new, changed = break_overlap(text, banned)
            if changed:
                container[key] = new
                adjusted.append(f"{section}.{key}")
    return adjusted


# ---------------------------------------------------------------------------
# Editorial
# ---------------------------------------------------------------------------


def _read_manifest(source_id: str) -> dict[str, Any] | None:
    try:
        path = paths.manifests_dir() / f"{source_id}.json"
        return read_json(path) if path.exists() else None
    except Exception:  # noqa: BLE001 - provenance lookup is best effort
        return None


def demo_sha256(candidate: dict[str, Any], manifest: dict[str, Any] | None) -> str:
    for source in (candidate, candidate.get("groundTruth") or {}):
        value = source.get("demoSha256")
        if value:
            return str(value)
    if manifest and manifest.get("demo", {}).get("sha256"):
        return str(manifest["demo"]["sha256"])
    try:  # the parsed match carries the demo hash too
        match_path = paths.parsed_dir(candidate["sourceId"]) / "match.json"
        if match_path.exists():
            return str(read_json(match_path).get("demoSha256", "unknown"))
    except Exception:  # noqa: BLE001
        pass
    return "unknown"


def build_editorial(candidate: dict[str, Any], f: Features, sit: Situation, ids: dict[str, str], main: MainPrior,
                    evidence: list[Signal], matrix: FollowupMatrix, cls_text: str, issues: list[str]) -> dict[str, Any]:
    manifest = _read_manifest(candidate["sourceId"])
    sha = demo_sha256(candidate, manifest)
    embedded = (candidate.get("groundTruth") or {}).get("source") or {}
    lane = (manifest or {}).get("rights", {}).get("contentLane") or embedded.get("contentLane") or "unknown (manifest not found)"
    reference = {
        "label": "Demo source (demo_source)",
        "detail": (
            f"kind=demo_source; sourceId={candidate['sourceId']}; candidateId={candidate['candidateId']}; "
            f"map={candidate.get('map')}; round={candidate.get('round')}; decisionTick={candidate.get('decisionTick')}; "
            f"decisionT={candidate.get('decisionT')}s; perspective={candidate.get('perspective')}; "
            f"category={candidate.get('category')}; demoSha256={sha}"
        ),
        "kind": "source",
    }
    score = candidate.get("score") or {}
    notes = [
        PROPOSED_RUBRIC_NOTE,
        "",
        "LANE: demo-grounded SYNTHETIC. The situation is inspired by a decision point in a real demo (see references) but the case "
        "does not claim to reproduce the match and contains no player names, Steam IDs, team names or player ids. "
        f"Content lane recorded on the source manifest: {lane}.",
        "The brief, evidence and actions use only candidate.playerKnown (plus map, perspective and category). The follow-up uses only "
        "candidate.followUp. Ground truth and the actual line appear only in the reveal. The historical line is shown for comparison "
        "and is NOT treated as the correct answer.",
        f"Candidate: {candidate['candidateId']} (score {score.get('total')}, category {candidate.get('category')}, "
        f"template family {sit.id}). Summary: {scrub(str(candidate.get('summary', '')))}",
        "",
        "PRIOR TABLE (every rubric value below is derivable from these rules and the player-known features):",
        *main.explain,
        *(f"normalisation: {line}" for line in main.normalised),
        f"follow-up: {cls_text}",
        *(f"  {line}" for line in matrix.explain),
        *(f"  locked {locked} -> " + ", ".join(f"{now}={matrix.cells[(locked, now)]}" for now in matrix.value_after)
          for locked in matrix.value_after),
        *(f"  {line}" for line in [
            f"evidence pairs: points = clamp(round(20 * (w_a + w_b) / (w_top1 + w_top2)), 3, 20) with per-signal weights from the "
            f"situation table and per-action overrides; signals: " + ", ".join(f"{s.id}({s.cls})" for s in evidence)]),
        f"Order of actions/qualifiers/responses is a deterministic hash of the candidate id; the top-ranked action is never first.",
    ]
    return {
        "status": "draft",
        "revision": ids["revision"],
        "rubricRevision": ids["rubricRevision"],
        "author": AUTHOR,
        "reviewers": [],
        "references": [reference],
        "knownIssues": issues,
        "notes": "\n".join(notes),
    }


# ---------------------------------------------------------------------------
# Public entry: build_case
# ---------------------------------------------------------------------------


def build_case(candidate: dict[str, Any], *, case_id: str | None = None) -> dict[str, Any]:
    cid = make_case_id(candidate, case_id)
    ids = derived_ids(cid)
    f = extract_features(candidate)
    sit = SITUATIONS[f.situation]
    main = compute_main_prior(sit, f)
    evidence = choose_evidence(sit, f)
    actions_ordered = order_actions(main.actions, candidate["candidateId"])

    brief, brief_issues = build_brief(candidate, f, sit, ids, main, evidence, actions_ordered)
    followup, matrix, cls_key, cls_text, followup_issues = build_followup(
        candidate, f, sit, ids, main, {fact["id"] for fact in brief["facts"]})
    reveal, reveal_issues = build_reveal(candidate, f, sit, ids, main, evidence, matrix, cls_key)
    rubric = build_rubric(sit, ids, main, brief, evidence, matrix, followup)

    issues: list[str] = [scrub(str(note)) for note in candidate.get("reviewNotes") or []]
    issues += brief_issues + followup_issues + reveal_issues
    issues.append(FOLLOWUP_MATRIX_ISSUE)
    issues += [
        "The option set (actions, qualifiers, follow-up responses) is a template for this situation family, not derived from the demo; "
        "a reviewer must confirm every option is playable on this map at this moment and that no defensible line is missing.",
        "The debrief reasoning (whyItWorks, cost, assumption, breaksWhen, strongestAlternative, counterfactual, evidence explanations, "
        "principle) is templated per situation family and needs human tactical review.",
        "Rubric ratings, evidence points and follow-up qualities are heuristic priors (see editorial.notes), not tactical judgements; "
        "time thresholds (defuse duration + 7 s, 25 s comfortable) are unreviewed assumptions.",
        "The reveal continuation is machine-rendered from demo events; check it against the demo before any review.",
        f"publicMetadata.case_number ({PLACEHOLDER_CASE_NUMBER}) and edition_date_utc ({PLACEHOLDER_EDITION_DATE}) are placeholders to set at scheduling.",
        "editorial.references cannot carry a demo_source kind (the editorial schema allows only background_reading or source); "
        "the demo source is recorded as kind 'source' with a structured detail string.",
    ]
    if len(main.actions) and sum(1 for a in main.actions if a.best_quality >= 70) < 2:
        issues.append("Under the proposed priors only one action reaches a defensible line (>= 70); the decision may not be a real dilemma here.")
    issues.extend(f"Prior normalisation: {line}" for line in main.normalised)

    case: dict[str, Any] = {
        "caseId": cid,
        "origin": "synthetic",
        "editorial": None,  # filled after the disclosure pass so knownIssues can mention adjustments
        "edition": {
            "editionId": ids["editionId"],
            "releaseAt": None,
            "officialEndAt": None,
            "graceEndAt": None,
            "publicMetadata": {
                "case_number": PLACEHOLDER_CASE_NUMBER,
                "edition_date_utc": PLACEHOLDER_EDITION_DATE,
                "estimated_minutes": 6,
                "focus": focus_for(sit, f),
                "origin_label": ORIGIN_LABEL,
            },
        },
        "brief": brief,
        "followup": followup,
        "reveal": reveal,
        "rubric": rubric,
    }
    adjusted = _enforce_no_overlap(case)
    if adjusted:
        issues.append("Wording of these follow-up/reveal fields was auto-adjusted to avoid a 6-word overlap with the brief; "
                      "review for readability: " + ", ".join(adjusted))
    case["editorial"] = build_editorial(candidate, f, sit, ids, main, evidence, matrix, cls_text, issues)
    # Re-order keys so the file reads editorial-first like the existing cases.
    return {key: case[key] for key in ("caseId", "origin", "editorial", "edition", "brief", "followup", "reveal", "rubric")}


def player_facing_text(case: dict[str, Any]) -> list[str]:
    """Every string a player can see (brief, follow-up, reveal, public metadata)."""
    texts: list[str] = []
    for section in ("brief", "followup", "reveal"):
        texts += [text for _, _, text in _walk_prose(case[section])]
    texts += [str(v) for v in case["edition"]["publicMetadata"].values()]
    return texts


def identity_leaks(case: dict[str, Any]) -> list[str]:
    return [text for text in player_facing_text(case) if has_identity(text)]


# ---------------------------------------------------------------------------
# draft_case: write + validate + review
# ---------------------------------------------------------------------------


def _existing_status(path: Path) -> str | None:
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("editorial", {}).get("status")
    except Exception:  # noqa: BLE001
        return None


def draft_case(candidate_path: Path, *, case_id: str | None = None, out_dir: Path | None = None,
               validate: bool = True, overwrite: bool = False) -> tuple[Path, dict[str, Any]]:
    from .review import write_review
    from .validate_run import run_validator

    candidate_path = Path(candidate_path)
    candidate = read_json(candidate_path)
    case = build_case(candidate, case_id=case_id)
    target_dir = Path(out_dir) if out_dir is not None else paths.cases_dir()
    target = target_dir / f"{case['caseId']}.json"
    if target.exists():
        status = _existing_status(target)
        if status != "draft":
            raise DraftRefused(f"{target} exists with status {status!r}; only files whose status is 'draft' can be regenerated.")
        if not overwrite:
            raise DraftRefused(f"{target} already exists; pass overwrite=True to replace this draft.")
    target_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(case, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    if validate:
        report = run_validator(case["caseId"], target)
    else:
        report = {"caseId": case["caseId"], "path": str(target), "validatorExitCode": None,
                  "errors": [], "warnings": [], "publishable": False, "validated": False}
    write_review(candidate_path, candidate, case, report)
    return target, report
