"""Reviewer summary (review.md) written next to the candidate. Reviewer-only: it may show ground truth."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .templates import SITUATIONS
from .features import extract_features
from .priors import compute_main_prior


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items) if items else "- (none)"


def write_review(candidate_path: Path, candidate: dict[str, Any], case: dict[str, Any], report: dict[str, Any]) -> Path:
    out = candidate_path.parent / "review.md"
    out.write_text(render_review(candidate_path, candidate, case, report), encoding="utf-8")
    return out


def render_review(candidate_path: Path, candidate: dict[str, Any], case: dict[str, Any], report: dict[str, Any]) -> str:
    f = extract_features(candidate)
    sit = SITUATIONS[f.situation]
    main = compute_main_prior(sit, f)
    score = candidate.get("score") or {}
    factors = score.get("factors") or {}
    view = candidate["playerKnown"]
    follow = candidate.get("followUp")
    truth = candidate.get("groundTruth") or {}
    lines: list[str] = []
    add = lines.append

    add(f"# Review: {case['caseId']}")
    add("")
    add("Reviewer-only file (may contain ground truth). Generated by `roundcraft-miner case draft`; the case is a DRAFT and the rubric "
        "is a PROPOSAL from heuristics, not tactical truth.")
    add("")
    add("## Candidate")
    add("")
    add(f"- candidate: `{candidate['candidateId']}` from `{candidate['sourceId']}`")
    add(f"- map {candidate.get('map')}, round {candidate.get('round')}, decision tick {candidate.get('decisionTick')} "
        f"(t = {candidate.get('decisionT')} s), perspective {candidate.get('perspective')}, category `{candidate.get('category')}`")
    add(f"- template family: `{sit.id}`")
    add(f"- summary: {candidate.get('summary')}")
    add("")
    add("## Score factors")
    add("")
    add(f"Total: **{score.get('total')}**")
    add("")
    add("| factor | value |")
    add("| --- | --- |")
    for key, value in sorted(factors.items()):
        add(f"| {key} | {value} |")
    add("")
    add("## Player-known facts (brief)")
    add("")
    add(_bullets([f"`{fact.get('status')}` {fact.get('text')} _(basis: {fact.get('basis', 'n/a')})_" for fact in view.get("facts") or []]))
    add("")
    add(f"Clock: {json.dumps(view.get('clock'))}; alive: {json.dumps(view.get('alive'))}; bomb: {json.dumps(view.get('bomb'))}")
    add("")
    add("## Follow-up (player-known new information)")
    add("")
    if follow:
        add(f"- kind `{follow.get('kind')}` at t = {follow.get('t')} s: {follow.get('summary')}")
        add(_bullets([f"`{fact.get('status')}` {fact.get('text')}" for fact in follow.get("newFacts") or []]))
    else:
        add("- none mined: the draft has a generic follow-up that needs authoring")
    add("")
    add("## What happened in the source round (historical, NOT the answer)")
    add("")
    add(f"- actual line: {candidate.get('actualLine')}")
    outcome = truth.get("outcome")
    if outcome:
        add(f"- outcome: {json.dumps(outcome, ensure_ascii=False)}")
    add(f"- timeline events mined after the decision: {len(truth.get('timelineAfter') or [])}")
    add("")
    add("## Disputed assumptions and known issues")
    add("")
    add(_bullets(case["editorial"]["knownIssues"]))
    add("")
    add("## Alternative plausible lines (from the template, in proposed rank order)")
    add("")
    add("| action | qualifiers | proposed tier | best line quality |")
    add("| --- | --- | --- | --- |")
    for action in main.actions:
        quals = "; ".join(f"{q.label} ({q.quality:g})" for q in action.qualifiers)
        add(f"| {action.label} | {quals} | {action.tier} ({action.tier_reason}) | {action.best_quality:g} |")
    add("")
    add("## Proposed follow-up qualities")
    add("")
    for response in case["rubric"]["followup"]["responses"]:
        label = next(r["label"] for r in case["followup"]["responses"] if r["id"] == response["responseId"])
        add(f"- {label}: {response['quality']}")
    add("")
    add("## Validation")
    add("")
    if report.get("validated"):
        add(f"- exit code {report.get('validatorExitCode')}, state {report.get('state')}, publishable: {report.get('publishable')}")
        add("- errors:")
        add(_bullets(report.get("errors") or []))
        add("- warnings:")
        add(_bullets(report.get("warnings") or []))
    else:
        add("- validator not run")
    add("")
    add("## Renders")
    add("")
    folder = candidate_path.parent
    links = [f"[{name}]({name})" for name in ("player-known.svg", "ground-truth.svg") if (folder / name).exists()]
    add(_bullets(links) if links else "- no SVG renders found next to the candidate (run `roundcraft-miner candidate render`)")
    add("")
    add(f"Draft file: `{case['caseId']}.json`")
    add("")
    return "\n".join(lines)
