import { createHash } from 'node:crypto'
import { DatabaseSync } from 'node:sqlite'
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { afterEach, describe, expect, it, vi } from 'vitest'

import { planBuild, runBuild } from './build'
import {
  canonicalJson,
  contentChecksum,
  defaultRoot,
  publishStatements,
  renderMigration,
  sqlString,
} from './lib'
import { previewWindow } from './lib'
import { previewSql, runPreview } from './preview'
import { caseFileSchema } from './schema'
import { WINDOW_A, fixtureJson, makeRoot, readyCase } from './test-helpers'
import type { Json } from './test-helpers'

const casePath = (id: string) => `content/cases/${id}.json`

function envelope(data: Json) {
  return caseFileSchema.parse(data)
}

function migrationsIn(root: string) {
  return readdirSync(join(root, 'migrations')).sort()
}

function silence() {
  vi.spyOn(console, 'log').mockImplementation(() => {})
  vi.spyOn(console, 'error').mockImplementation(() => {})
  vi.spyOn(console, 'warn').mockImplementation(() => {})
}

describe('canonical JSON and checksums', () => {
  it('sorts keys recursively and ignores key order', () => {
    expect(canonicalJson({ b: 1, a: { d: [3, { z: 1, y: 2 }], c: 'x' } })).toBe(
      '{"a":{"c":"x","d":[3,{"y":2,"z":1}]},"b":1}',
    )
  })

  it('computes a stable sha256 of the four canonical payloads', () => {
    const data = readyCase('cand_001', WINDOW_A)
    const file = envelope(data)
    const expected = createHash('sha256')
      .update(
        canonicalJson({
          brief: data.brief,
          followup: data.followup,
          reveal: data.reveal,
          rubric: data.rubric,
        }),
      )
      .digest('hex')

    expect(contentChecksum(file)).toBe(`sha256:${expected}`)
    // Reordering keys, editorial metadata and the schedule must not matter.
    const shuffled = envelope({
      ...data,
      brief: Object.fromEntries(Object.entries(data.brief).reverse()),
      editorial: { ...data.editorial, notes: 'changed' },
    })
    expect(contentChecksum(shuffled)).toBe(contentChecksum(file))
  })

  it('changes when any payload changes', () => {
    const base = contentChecksum(envelope(readyCase('cand_001', WINDOW_A)))
    const changed = readyCase('cand_001', WINDOW_A, (d) => {
      d.reveal.principle += ' Also.'
    })

    expect(contentChecksum(envelope(changed))).not.toBe(base)
  })
})

describe('generated SQL', () => {
  const tricky = readyCase('cand_001', WINDOW_A, (d) => {
    d.reveal.debrief.cost = `It's a "cost"; DROP TABLE cases; -- and 'quoted' \\ backslash ünïcode 日本`
  })

  it('is deterministic and carries the generated header', () => {
    const file = envelope(tricky)
    const first = renderMigration('publish', file)

    expect(renderMigration('publish', file)).toBe(first)
    expect(first.startsWith('-- Generated by npm run content:build — do not edit\n')).toBe(true)
    expect(first).toContain(`-- content-checksum: ${contentChecksum(file)}`)
  })

  it('doubles single quotes', () => {
    expect(sqlString("it's")).toBe("'it''s'")
    expect(renderMigration('publish', envelope(tricky))).toContain("It''s a")
  })

  it('loads into SQLite and round-trips payloads, checksums and the edition', () => {
    const file = envelope(tricky)
    const database = new DatabaseSync(':memory:')
    database.exec('PRAGMA foreign_keys = ON')
    database.exec(readFileSync(join(defaultRoot(), 'migrations', '0001_initial.sql'), 'utf8'))
    database.exec(renderMigration('publish', file))
    // D1 applies each migration once; a second application must fail loudly, never skip silently.
    expect(() => database.exec(renderMigration('publish', file))).toThrow(/UNIQUE constraint failed/)

    const revision = database.prepare('SELECT status, checksum FROM case_revisions').get()
    const brief = database.prepare('SELECT payload_json, checksum FROM case_public_briefs').get() as {
      payload_json: string
      checksum: string
    }
    const reveal = database.prepare('SELECT payload_json FROM case_reveals').get() as { payload_json: string }
    const edition = database
      .prepare('SELECT publication_status, release_at, official_end_at, grace_end_at, public_metadata_json FROM editions')
      .get() as Record<string, string>

    expect(revision).toMatchObject({ status: 'locked', checksum: contentChecksum(file) })
    expect(brief.payload_json).toBe(canonicalJson(tricky.brief))
    expect(brief.checksum).toBe(`sha256:${createHash('sha256').update(canonicalJson(tricky.brief)).digest('hex')}`)
    expect(JSON.parse(reveal.payload_json)).toEqual(tricky.reveal)
    expect(edition).toMatchObject({
      publication_status: 'released',
      release_at: WINDOW_A.releaseAt,
      official_end_at: WINDOW_A.officialEndAt,
      grace_end_at: WINDOW_A.graceEndAt,
    })
    expect(JSON.parse(edition['public_metadata_json'] ?? '')).toEqual(tricky.edition.publicMetadata)
    expect(database.prepare('SELECT COUNT(*) AS n FROM cases').get()).toEqual({ n: 1 })
    expect(database.prepare("SELECT created_at FROM cases").get()).toEqual({
      created_at: expect.stringMatching(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/),
    })
  })

  it('renders a withdraw migration that retires edition and revision', () => {
    const file = envelope(readyCase('cand_001', WINDOW_A))
    const database = new DatabaseSync(':memory:')
    database.exec(readFileSync(join(defaultRoot(), 'migrations', '0001_initial.sql'), 'utf8'))
    database.exec(renderMigration('publish', file))
    database.exec(renderMigration('withdraw', file))

    expect(database.prepare('SELECT publication_status FROM editions').get()).toEqual({ publication_status: 'withdrawn' })
    expect(database.prepare('SELECT status FROM case_revisions').get()).toEqual({ status: 'withdrawn' })
  })

  it('previews idempotently with a window covering now', () => {
    const file = envelope(fixtureJson())
    const now = new Date('2026-09-29T12:00:00.000Z')
    const window = previewWindow(now)
    const database = new DatabaseSync(':memory:')
    database.exec(readFileSync(join(defaultRoot(), 'migrations', '0001_initial.sql'), 'utf8'))
    database.exec('PRAGMA foreign_keys = ON')

    database.exec(previewSql(file, now))
    // A later preview moves the window and updates the payloads in place.
    database.exec(previewSql(file, new Date('2026-10-01T12:00:00.000Z')))
    database.exec(previewSql(file, now))

    const edition = database.prepare('SELECT release_at, official_end_at, public_metadata_json FROM editions').get() as Record<string, string>
    expect(window.releaseAt < now.toISOString()).toBe(true)
    expect(window.officialEndAt > now.toISOString()).toBe(true)
    expect(edition['release_at']).toBe(window.releaseAt)
    expect(JSON.parse(edition['public_metadata_json'] ?? '')).toMatchObject({ edition_date_utc: '2026-09-29' })
    expect(database.prepare('SELECT COUNT(*) AS n FROM editions').get()).toEqual({ n: 1 })
    expect(database.prepare('SELECT COUNT(*) AS n FROM case_rubrics').get()).toEqual({ n: 1 })
    expect(database.prepare('SELECT status FROM case_revisions').get()).toEqual({ status: 'locked' })
  })

  it('refuses to render a publish migration without a schedule', () => {
    const file = envelope(readyCase('cand_001', WINDOW_A, (d) => { d.edition.releaseAt = null }))

    expect(() => publishStatements(file, { mode: 'insert' })).toThrow(/no complete edition schedule/)
  })
})

describe('content:build', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('writes the next numbered migration for a ready case and is then up to date', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })

    expect(runBuild([], root)).toBe(0)
    expect(migrationsIn(root)).toEqual([
      '0001_initial.sql',
      '0002_seed_cases.sql',
      '0003_publish_case_cand_001_case_revision_cand_001.sql',
    ])

    const before = readFileSync(join(root, 'migrations', migrationsIn(root)[2] ?? ''), 'utf8')
    expect(runBuild([], root)).toBe(0)
    expect(migrationsIn(root)).toHaveLength(3)
    expect(readFileSync(join(root, 'migrations', migrationsIn(root)[2] ?? ''), 'utf8')).toBe(before)
    expect(runBuild(['--check'], root)).toBe(0)
  })

  it('numbers several new migrations consecutively', () => {
    const root = makeRoot({
      [casePath('case_one_001')]: readyCase('one_001', WINDOW_A),
      [casePath('case_two_001')]: readyCase('two_001', {
        releaseAt: '2027-02-01T00:00:00.000Z',
        officialEndAt: '2027-02-02T00:00:00.000Z',
        graceEndAt: '2027-02-02T12:00:00.000Z',
      }),
    })
    const plan = planBuild({ root })

    expect(plan.errors).toEqual([])
    expect(plan.writes.map(({ fileName }) => fileName.slice(0, 4))).toEqual(['0003', '0004'])
  })

  it('--check fails when a ready case has no migration, without writing', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })

    expect(runBuild(['--check'], root)).toBe(1)
    expect(migrationsIn(root)).toHaveLength(2)
  })

  it('--check detects locked content that changed after generation', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    runBuild([], root)

    const changed = readyCase('cand_001', WINDOW_A, (d) => { d.reveal.principle += ' Edited later.' })
    writeFileSync(join(root, casePath('case_cand_001')), JSON.stringify(changed))
    const plan = planBuild({ root, check: true })

    expect(plan.errors.join('\n')).toMatch(/content changed after 0003_publish_case_cand_001/)
    expect(runBuild(['--check'], root)).toBe(1)
    expect(runBuild([], root)).toBe(1)
    expect(migrationsIn(root)).toHaveLength(3)
  })

  it('does not treat editorial-only edits as a content change', () => {
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    silence()
    runBuild([], root)
    const edited = readyCase('cand_001', WINDOW_A, (d) => { d.editorial.notes = 'Now with notes.' })
    writeFileSync(join(root, casePath('case_cand_001')), JSON.stringify(edited))

    expect(planBuild({ root, check: true }).errors).toEqual([])
  })

  it('rejects a new revision id under an already published case id', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    runBuild([], root)
    const revised = JSON.stringify(readyCase('cand_001', WINDOW_A)).replaceAll('case_revision_cand_001', 'case_revision_cand_002')
    writeFileSync(join(root, casePath('case_cand_001')), revised)

    expect(planBuild({ root, check: true }).errors.join('\n')).toMatch(/already published/)
  })

  it('refuses reverting a published case to a draft status', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    runBuild([], root)
    writeFileSync(
      join(root, casePath('case_cand_001')),
      JSON.stringify(readyCase('cand_001', WINDOW_A, (d) => { d.editorial.status = 'draft' })),
    )

    expect(planBuild({ root, check: true }).errors.join('\n')).toMatch(/already published/)
  })

  it('refuses fixtures, drafts and invalid ready cases', () => {
    silence()
    const invalidReady = readyCase('bad_001', WINDOW_A, (d) => { d.rubric.evidence.shift() })
    const draft = readyCase('draft_001', WINDOW_A, (d) => { d.editorial.status = 'draft' })
    const root = makeRoot({
      'content/fixtures/case_smoke_001.json': fixtureJson(),
      [casePath('case_draft_001')]: draft,
      [casePath('case_bad_001')]: invalidReady,
    })

    expect(planBuild({ root, caseId: 'case_smoke_001' }).errors.join('\n')).toMatch(/fixtures are never published/)
    expect(planBuild({ root, caseId: 'case_draft_001' }).errors.join('\n')).toMatch(/only "ready" or "withdrawn"/)
    expect(planBuild({ root, caseId: 'case_bad_001' }).errors.join('\n')).toMatch(/validation failed/)
    expect(planBuild({ root, caseId: 'nope' }).errors.join('\n')).toMatch(/No case named/)
    // Without --case, fixtures and drafts are skipped silently; the invalid ready case still fails.
    const all = planBuild({ root })
    expect(all.writes).toEqual([])
    expect(all.errors).toHaveLength(1)
  })

  it('writes a withdraw migration once, only for previously published cases', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    runBuild([], root)
    writeFileSync(
      join(root, casePath('case_cand_001')),
      JSON.stringify(readyCase('cand_001', WINDOW_A, (d) => { d.editorial.status = 'withdrawn' })),
    )

    expect(runBuild(['--check'], root)).toBe(1)
    expect(runBuild([], root)).toBe(0)
    expect(migrationsIn(root)[3]).toBe('0004_withdraw_case_cand_001_case_revision_cand_001.sql')
    expect(runBuild([], root)).toBe(0)
    expect(migrationsIn(root)).toHaveLength(4)
    expect(runBuild(['--check'], root)).toBe(0)

    const neverPublished = makeRoot({
      [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A, (d) => { d.editorial.status = 'withdrawn' }),
    })
    expect(planBuild({ root: neverPublished }).writes).toEqual([])
  })

  it('flags a published case whose file was deleted or corrupted', () => {
    silence()
    const root = makeRoot({ [casePath('case_cand_001')]: readyCase('cand_001', WINDOW_A) })
    runBuild([], root)
    writeFileSync(join(root, casePath('case_other_001')), JSON.stringify(readyCase('other_001', { ...WINDOW_A, releaseAt: '2028-01-01T00:00:00.000Z', officialEndAt: '2028-01-02T00:00:00.000Z', graceEndAt: '2028-01-02T12:00:00.000Z' })))
    writeFileSync(join(root, casePath('case_cand_001')), JSON.stringify(readyCase('cand_001', WINDOW_A, (d) => { d.editorial.status = 'withdrawn' })))
    runBuild([], root)
    // A corrupt file and a deleted file both orphan the published migrations.
    writeFileSync(join(root, casePath('case_cand_001')), '{')
    expect(planBuild({ root, check: true }).errors.join('\n')).toMatch(/no valid case file/)
    rmSync(join(root, casePath('case_cand_001')))
    expect(planBuild({ root, check: true }).errors.join('\n')).toMatch(/no valid case file/)
  })
})

describe('content:preview', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('refuses --remote before doing anything', () => {
    silence()

    expect(runPreview(['case_smoke_001', '--remote'])).toBe(2)
    expect(runPreview(['--remote=true', 'case_smoke_001'])).toBe(2)
  })

  it('validates its arguments', () => {
    silence()

    expect(runPreview([])).toBe(2)
    expect(runPreview(['a', 'b'])).toBe(2)
    expect(runPreview(['--bogus', 'a'])).toBe(2)
    expect(runPreview(['missing_case'])).toBe(2)
  })

  it('prints SQL for the fixture without touching any database', () => {
    const write = vi.spyOn(process.stdout, 'write').mockImplementation(() => true)

    expect(runPreview(['case_smoke_001', '--print'])).toBe(0)
    expect(String(write.mock.calls[0]?.[0])).toContain('INSERT INTO editions')
  })
})
