import { createHash } from 'node:crypto'
import { readdirSync, readFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type { CaseFileEnvelope } from './schema'

export const GENERATED_HEADER =
  '-- Generated by npm run content:build — do not edit'

export function defaultRoot(): string {
  return fileURLToPath(new URL('../../', import.meta.url))
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

export interface LoadedCase {
  /** File stem, e.g. case_inferno_banana_001. */
  readonly id: string
  /** Repository-relative path using forward slashes. */
  readonly file: string
  readonly dir: 'cases' | 'fixtures'
  readonly data?: unknown
  readonly parseError?: string
}

export function loadCases(root: string): LoadedCase[] {
  const loaded: LoadedCase[] = []

  for (const dir of ['cases', 'fixtures'] as const) {
    let names: string[]
    try {
      names = readdirSync(join(root, 'content', dir))
    } catch {
      continue
    }

    for (const name of names.filter((entry) => entry.endsWith('.json')).sort()) {
      const file = `content/${dir}/${name}`
      const id = basename(name, '.json')

      try {
        const data: unknown = JSON.parse(
          readFileSync(join(root, 'content', dir, name), 'utf8'),
        )
        loaded.push({ id, file, dir, data })
      } catch (error) {
        loaded.push({
          id,
          file,
          dir,
          parseError: error instanceof Error ? error.message : String(error),
        })
      }
    }
  }

  return loaded
}

// ---------------------------------------------------------------------------
// Canonical JSON and checksums
// ---------------------------------------------------------------------------

/** JSON with recursively sorted object keys and no insignificant whitespace. */
export function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(',')}]`
  }

  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, item]) => item !== undefined)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))

    return `{${entries
      .map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`)
      .join(',')}}`
  }

  return JSON.stringify(value)
}

export function sha256Checksum(text: string): string {
  return `sha256:${createHash('sha256').update(text, 'utf8').digest('hex')}`
}

export type PayloadName = 'brief' | 'followup' | 'reveal' | 'rubric'

export function payloadsOf(
  caseFile: CaseFileEnvelope,
): Record<PayloadName, Record<string, unknown>> {
  return {
    brief: caseFile.brief,
    followup: caseFile.followup,
    reveal: caseFile.reveal,
    rubric: caseFile.rubric,
  }
}

/** Checksum of the four payloads; stored on case_revisions. */
export function contentChecksum(caseFile: CaseFileEnvelope): string {
  return sha256Checksum(canonicalJson(payloadsOf(caseFile)))
}

// ---------------------------------------------------------------------------
// SQL generation (pure, parameter-free, deterministic)
// ---------------------------------------------------------------------------

export function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

function sqlJson(value: unknown): string {
  return `json(${sqlString(canonicalJson(value))})`
}

/** Same millisecond ISO format the Worker writes with toISOString(). */
const NOW_SQL = "strftime('%Y-%m-%dT%H:%M:%fZ', 'now')"

export interface EditionWindow {
  readonly releaseAt: string
  readonly officialEndAt: string
  readonly graceEndAt: string
}

/** Window used by local previews and tests: opened an hour ago, ends in 30 days. */
export function previewWindow(now: Date): EditionWindow {
  const hour = 60 * 60 * 1000
  const day = 24 * hour

  return {
    releaseAt: new Date(now.getTime() - hour).toISOString(),
    officialEndAt: new Date(now.getTime() + 30 * day).toISOString(),
    graceEndAt: new Date(now.getTime() + 31 * day).toISOString(),
  }
}

export interface PublishSqlOptions {
  /**
   * "insert": plain INSERT for append-only production migrations, so a
   * constraint violation fails the deploy loudly instead of being skipped.
   * "upsert": idempotent refresh for local previews.
   */
  readonly mode: 'insert' | 'upsert'
  /** Overrides the case's own schedule (previews). */
  readonly window?: EditionWindow
  /** Merged over edition.publicMetadata (previews). */
  readonly metadata?: Readonly<Record<string, unknown>>
}

export function scheduleOf(
  caseFile: CaseFileEnvelope,
  window?: EditionWindow,
): EditionWindow {
  if (window) return window

  const { releaseAt, officialEndAt, graceEndAt } = caseFile.edition
  if (releaseAt === null || officialEndAt === null || graceEndAt === null) {
    throw new Error(`Case ${caseFile.caseId} has no complete edition schedule`)
  }

  return { releaseAt, officialEndAt, graceEndAt }
}

export function publishStatements(
  caseFile: CaseFileEnvelope,
  options: PublishSqlOptions,
): string[] {
  const revision = caseFile.editorial.revision
  const schedule = scheduleOf(caseFile, options.window)
  const payloads = payloadsOf(caseFile)
  const metadata = { ...caseFile.edition.publicMetadata, ...options.metadata }
  const schemaVersion = Number(caseFile.brief['schemaVersion'] ?? 1)
  const insert = 'INSERT'
  const upsert = (conflictTarget: string, columns: readonly string[]) =>
    options.mode === 'upsert'
      ? `\nON CONFLICT (${conflictTarget}) DO UPDATE SET ${columns
          .map((column) => `${column} = excluded.${column}`)
          .join(', ')}`
      : ''

  const payloadInsert = (
    table: string,
    name: PayloadName,
    extra?: { readonly column: string; readonly value: string },
  ) => {
    const columns = ['case_revision', ...(extra ? [extra.column] : []), 'payload_json', 'checksum', 'created_at']
    const values = [
      sqlString(revision),
      ...(extra ? [sqlString(extra.value)] : []),
      sqlJson(payloads[name]),
      sqlString(sha256Checksum(canonicalJson(payloads[name]))),
      NOW_SQL,
    ]
    const conflictTarget = extra ? extra.column : 'case_revision'
    const updated = extra
      ? ['case_revision', 'payload_json', 'checksum']
      : ['payload_json', 'checksum']

    return `${insert} INTO ${table} (${columns.join(', ')})\nVALUES (${values.join(', ')})${upsert(conflictTarget, updated)}`
  }

  return [
    `${insert} INTO cases (case_id, origin, created_at)\nVALUES (${sqlString(caseFile.caseId)}, ${sqlString(caseFile.origin)}, ${NOW_SQL})${upsert('case_id', ['origin'])}`,
    `${insert} INTO case_revisions (case_revision, case_id, schema_version, checksum, status, created_at)\nVALUES (${sqlString(revision)}, ${sqlString(caseFile.caseId)}, ${schemaVersion}, ${sqlString(contentChecksum(caseFile))}, 'locked', ${NOW_SQL})${upsert('case_revision', ['checksum', 'status'])}`,
    payloadInsert('case_public_briefs', 'brief'),
    payloadInsert('case_followups', 'followup'),
    payloadInsert('case_reveals', 'reveal'),
    payloadInsert('case_rubrics', 'rubric', {
      column: 'rubric_revision',
      value: caseFile.editorial.rubricRevision,
    }),
    `${insert} INTO editions (edition_id, case_revision, release_at, official_end_at, grace_end_at, publication_status, public_metadata_json, created_at)\nVALUES (${sqlString(caseFile.edition.editionId)}, ${sqlString(revision)}, ${sqlString(schedule.releaseAt)}, ${sqlString(schedule.officialEndAt)}, ${sqlString(schedule.graceEndAt)}, 'released', ${sqlJson(metadata)}, ${NOW_SQL})${upsert('edition_id', ['release_at', 'official_end_at', 'grace_end_at', 'publication_status', 'public_metadata_json'])}`,
  ]
}

export function withdrawStatements(caseFile: CaseFileEnvelope): string[] {
  return [
    `UPDATE editions SET publication_status = 'withdrawn'\nWHERE edition_id = ${sqlString(caseFile.edition.editionId)}`,
    `UPDATE case_revisions SET status = 'withdrawn'\nWHERE case_revision = ${sqlString(caseFile.editorial.revision)}`,
  ]
}

function headerLines(
  kind: 'publish' | 'withdraw',
  caseFile: CaseFileEnvelope,
): string[] {
  return [
    GENERATED_HEADER,
    `-- kind: ${kind}`,
    `-- case: ${caseFile.caseId}`,
    `-- revision: ${caseFile.editorial.revision}`,
    `-- edition: ${caseFile.edition.editionId}`,
    `-- content-checksum: ${contentChecksum(caseFile)}`,
  ]
}

export function renderMigration(
  kind: 'publish' | 'withdraw',
  caseFile: CaseFileEnvelope,
): string {
  const statements =
    kind === 'publish'
      ? publishStatements(caseFile, { mode: 'insert' })
      : withdrawStatements(caseFile)

  return `${headerLines(kind, caseFile).join('\n')}\n\n${statements
    .map((statement) => `${statement};`)
    .join('\n\n')}\n`
}

export function migrationFileName(
  number: number,
  kind: 'publish' | 'withdraw',
  caseFile: CaseFileEnvelope,
): string {
  return `${String(number).padStart(4, '0')}_${kind}_${caseFile.caseId}_${caseFile.editorial.revision}.sql`
}

// ---------------------------------------------------------------------------
// Existing migrations
// ---------------------------------------------------------------------------

export interface GeneratedMigration {
  readonly fileName: string
  readonly kind: 'publish' | 'withdraw'
  readonly caseId: string
  readonly revision: string
  readonly contentChecksum: string
  readonly text: string
}

export interface MigrationIndex {
  readonly highestNumber: number
  readonly generated: readonly GeneratedMigration[]
}

export function indexMigrations(root: string): MigrationIndex {
  const directory = join(root, 'migrations')
  let names: string[] = []
  try {
    names = readdirSync(directory).filter((name) => name.endsWith('.sql')).sort()
  } catch {
    // No migrations directory yet.
  }

  let highestNumber = 0
  const generated: GeneratedMigration[] = []

  for (const name of names) {
    const match = /^(\d+)_/.exec(name)
    if (match?.[1]) highestNumber = Math.max(highestNumber, Number(match[1]))

    const text = readFileSync(join(directory, name), 'utf8')
    if (!text.startsWith(GENERATED_HEADER)) continue

    const field = (key: string) =>
      new RegExp(`^-- ${key}: (.+)$`, 'm').exec(text)?.[1]?.trim()
    const kind = field('kind')
    const caseId = field('case')
    const revision = field('revision')
    const checksum = field('content-checksum')

    if (
      (kind === 'publish' || kind === 'withdraw') &&
      caseId &&
      revision &&
      checksum
    ) {
      generated.push({
        fileName: name,
        kind,
        caseId,
        revision,
        contentChecksum: checksum,
        text,
      })
    }
  }

  return { highestNumber, generated }
}
