import { spawnSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

import { contentChecksum, defaultRoot, loadCases, previewWindow, publishStatements } from './lib'
import { caseFileSchema } from './schema'
import type { CaseFileEnvelope } from './schema'
import { validateCase } from './validate'

const D1_DATABASE = 'roundcraft-prod'

/**
 * Idempotent SQL that makes the case playable right now in a local database.
 * Re-running refreshes the same rows instead of failing or duplicating them.
 */
export function previewSql(caseFile: CaseFileEnvelope, now = new Date()): string {
  const statements = publishStatements(caseFile, {
    mode: 'upsert',
    window: previewWindow(now),
    metadata: { edition_date_utc: now.toISOString().slice(0, 10) },
  })

  return [
    '-- Local preview generated by npm run content:preview — never applied remotely.',
    `-- case: ${caseFile.caseId}  revision: ${caseFile.editorial.revision}  content-checksum: ${contentChecksum(caseFile)}`,
    '',
    ...statements.map((statement) => `${statement};\n`),
  ].join('\n')
}

function run(root: string, args: readonly string[]): number {
  const result = spawnSync(join(root, 'node_modules', '.bin', 'wrangler'), [...args], {
    cwd: root,
    stdio: 'inherit',
  })
  return result.status ?? 1
}

export function runPreview(argv: readonly string[], root = defaultRoot()): number {
  if (argv.some((arg) => arg === '--remote' || arg.startsWith('--remote='))) {
    console.error('content:preview only ever writes to the LOCAL database; --remote is refused.')
    return 2
  }

  const print = argv.includes('--print')
  const positional = argv.filter((arg) => !arg.startsWith('--'))
  const unknown = argv.filter((arg) => arg.startsWith('--') && arg !== '--print')
  if (unknown.length > 0 || positional.length !== 1 || !positional[0]) {
    console.error('Usage: npm run content:preview -- <case-or-fixture-id> [--print]')
    return 2
  }

  const id = positional[0]
  const loaded = loadCases(root).find((entry) => entry.id === id)
  if (!loaded) {
    console.error(`No case or fixture named "${id}" under content/`)
    return 2
  }

  const parsed = caseFileSchema.safeParse(loaded.data)
  if (!parsed.success) {
    console.error(`${loaded.file} is not a valid case file; run npm run content:validate -- --case ${id}`)
    return 1
  }

  const report = validateCase(loaded)
  if (report.errors.length > 0) {
    console.warn(
      `warning: ${id} has ${report.errors.length} validation error(s) and could not be published; previewing anyway (run npm run content:validate -- --case ${id}).`,
    )
  }

  const sql = previewSql(parsed.data)
  if (print) {
    process.stdout.write(sql)
    return 0
  }

  const directory = mkdtempSync(join(tmpdir(), 'roundcraft-preview-'))
  const file = join(directory, `${id}.sql`)
  try {
    writeFileSync(file, sql)
    const migrated = run(root, ['d1', 'migrations', 'apply', D1_DATABASE, '--local'])
    if (migrated !== 0) return migrated
    const applied = run(root, ['d1', 'execute', D1_DATABASE, '--local', '--file', file])
    if (applied !== 0) return applied
  } finally {
    rmSync(directory, { recursive: true, force: true })
  }

  console.log(
    `\nPreviewing ${id} locally. Start the app with "npm run dev" and open Today; the case is playable for the next 30 days.`,
  )
  return 0
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = runPreview(process.argv.slice(2))
}
